/* Generated by QSI

 Date: 2020-08-07
 Span: 411:1 - 416:14
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("A_ArrayExpr")]
    internal sealed class A_ArrayExpr : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_A_ArrayExpr; }
        }

        public IPg10Node[] elements { get; set; }

        public int location { get; set; }
    }
}
