/* Generated by QSI

 Date: 2020-08-07
 Span: 411:1 - 416:14
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("A_ArrayExpr")]
    internal class A_ArrayExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_A_ArrayExpr;

        public NodeTag? type { get; set; }

        public IPg10Node[] elements { get; set; }
    }
}
