/* Generated by QSI

 Date: 2020-08-07
 Span: 284:1 - 289:10
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("A_Const")]
    internal sealed class A_Const : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_A_Const; }
        }

        public Value val { get; set; }

        public int location { get; set; }
    }
}
