/* Generated by QSI

 Date: 2020-08-12
 Span: 251:1 - 269:14
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum A_Expr_Kind
    {
        AEXPR_OP = 0,
        AEXPR_OP_ANY = 1,
        AEXPR_OP_ALL = 2,
        AEXPR_DISTINCT = 3,
        AEXPR_NOT_DISTINCT = 4,
        AEXPR_NULLIF = 5,
        AEXPR_OF = 6,
        AEXPR_IN = 7,
        AEXPR_LIKE = 8,
        AEXPR_ILIKE = 9,
        AEXPR_SIMILAR = 10,
        AEXPR_BETWEEN = 11,
        AEXPR_NOT_BETWEEN = 12,
        AEXPR_BETWEEN_SYM = 13,
        AEXPR_NOT_BETWEEN_SYM = 14,
        AEXPR_PAREN = 15
    }
}
