/* Generated by QSI

 Date: 2020-08-07
 Span: 401:1 - 406:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("A_Indirection")]
    internal sealed class A_Indirection : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_A_Indirection; }
        }

        public IPg10Node arg { get; set; }

        public IPg10Node[] indirection { get; set; }
    }
}
