/* Generated by QSI

 Date: 2020-08-07
 Span: 367:1 - 370:9
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("A_Star")]
    internal sealed class A_Star : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_A_Star; }
        }
    }
}
