/* Generated by QSI

 Date: 2020-08-12
 Span: 52:1 - 52:30
 File: src/postgres/include/commands/trigger.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class AfterTriggersTableData
    {
    }
}
