/* Generated by QSI

 Date: 2020-08-12
 Span: 780:1 - 793:6
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Agg")]
    internal class Agg : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Agg;

        public Plan plan { get; set; }

        public AggStrategy? aggstrategy { get; set; }

        public AggSplit? aggsplit { get; set; }

        public int? numCols { get; set; }

        public short[] grpColIdx { get; set; }

        public uint[] grpOperators { get; set; }

        public int? numGroups { get; set; }

        public Bitmapset[] aggParams { get; set; }

        public IPg10Node[] groupingSets { get; set; }

        public IPg10Node[] chain { get; set; }
    }
}
