/* Generated by QSI

 Date: 2020-08-07
 Span: 1457:1 - 1466:10
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AggPath")]
    internal class AggPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AggPath;

        public Path path { get; set; }

        public Path subpath { get; set; }

        public AggStrategy? aggstrategy { get; set; }

        public AggSplit? aggsplit { get; set; }

        public double? numGroups { get; set; }

        public IPg10Node[] groupClause { get; set; }

        public IPg10Node[] qual { get; set; }
    }
}
