/* Generated by QSI

 Date: 2020-08-12
 Span: 291:1 - 312:9
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Aggref")]
    internal class Aggref : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Aggref;

        public IPg10ExpressionNode xpr { get; set; }

        public uint? aggfnoid { get; set; }

        public uint? aggtype { get; set; }

        public uint? aggcollid { get; set; }

        public uint? inputcollid { get; set; }

        public uint? aggtranstype { get; set; }

        public IPg10Node[] aggargtypes { get; set; }

        public IPg10Node[] aggdirectargs { get; set; }

        public IPg10Node[] args { get; set; }

        public IPg10Node[] aggorder { get; set; }

        public IPg10Node[] aggdistinct { get; set; }

        public IPg10ExpressionNode aggfilter { get; set; }

        public bool? aggstar { get; set; }

        public bool? aggvariadic { get; set; }

        public char? aggkind { get; set; }

        public uint? agglevelsup { get; set; }

        public AggSplit? aggsplit { get; set; }
    }
}
