/* Generated by QSI

 Date: 2020-08-07
 Span: 656:1 - 661:18
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AggrefExprState")]
    internal sealed class AggrefExprState : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AggrefExprState; }
        }

        public Aggref aggref { get; set; }

        public int aggno { get; set; }
    }
}
