/* Generated by QSI

 Date: 2020-08-07
 Span: 1789:9 - 1789:36
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class AggStatePerPhaseData
    {
    }
}
