/* Generated by QSI

 Date: 2020-08-12
 Span: 1787:9 - 1787:36
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class AggStatePerTransData
    {
    }
}
