/* Generated by QSI

 Date: 2020-08-07
 Span: 1787:9 - 1787:36
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class AggStatePerTransData
    {
    }
}
