/* Generated by QSI

 Date: 2020-08-07
 Span: 1788:9 - 1788:36
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class AggStatePerGroupData
    {
    }
}
