/* Generated by QSI

 Date: 2020-08-07
 Span: 757:1 - 765:11
 File: src/postgres/include/nodes/nodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum AggSplit
    {
        AGGSPLIT_SIMPLE = 0,
        AGGSPLIT_INITIAL_SERIAL = 6,
        AGGSPLIT_FINAL_DESERIAL = 9
    }
}
