/* Generated by QSI

 Date: 2020-08-07
 Span: 735:1 - 741:14
 File: src/postgres/include/nodes/nodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum AggStrategy
    {
        AGG_PLAIN = 0,
        AGG_SORTED = 1,
        AGG_HASHED = 2,
        AGG_MIXED = 3
    }
}
