/* Generated by QSI

 Date: 2020-08-12
 Span: 1786:9 - 1786:34
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class AggStatePerAggData
    {
    }
}
