/* Generated by QSI

 Date: 2020-08-07
 Span: 1790:9 - 1790:35
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class AggStatePerHashData
    {
    }
}
