/* Generated by QSI

 Date: 2020-08-07
 Span: 39:1 - 44:8
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Alias")]
    internal class Alias : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Alias;

        public NodeTag? type { get; set; }

        public string aliasname { get; set; }

        public IPg10Node[] colnames { get; set; }
    }
}
