/* Generated by QSI

 Date: 2020-08-12
 Span: 139:1 - 151:18
 File: src/postgres/src_backend_utils_mmgr_aset.c

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AllocSetContext")]
    internal class AllocSetContext : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AllocSetContext;

        public MemoryContextData header { get; set; }

        public AllocBlockData[] blocks { get; set; }

        public AllocChunkData[][] freelist { get; set; }

        public uint? initBlockSize { get; set; }

        public uint? maxBlockSize { get; set; }

        public uint? nextBlockSize { get; set; }

        public uint? allocChunkLimit { get; set; }

        public AllocBlockData[] keeper { get; set; }
    }
}
