/* Generated by QSI

 Date: 2020-08-12
 Span: 180:1 - 198:19
 File: src/postgres/src_backend_utils_mmgr_aset.c

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class AllocChunkData
    {
        public uint? size { get; set; }

        public object?[] aset { get; set; }
    }
}
