/* Generated by QSI

 Date: 2020-08-12
 Span: 2391:1 - 2397:21
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterEventTrigStmt")]
    internal class AlterEventTrigStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterEventTrigStmt;

        public string trigname { get; set; }

        public char? tgenabled { get; set; }
    }
}
