/* Generated by QSI

 Date: 2020-08-12
 Span: 3063:1 - 3067:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterSystemStmt")]
    internal class AlterSystemStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterSystemStmt;

        public VariableSetStmt setstmt { get; set; }
    }
}
