/* Generated by QSI

 Date: 2020-08-07
 Span: 2976:1 - 2985:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterEnumStmt")]
    internal sealed class AlterEnumStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterEnumStmt; }
        }

        public IPg10Node[] typeName { get; set; }

        public string oldVal { get; set; }

        public string newVal { get; set; }

        public string newValNeighbor { get; set; }

        public bool newValIsAfter { get; set; }

        public bool skipIfNewValExists { get; set; }
    }
}
