/* Generated by QSI

 Date: 2020-08-07
 Span: 2325:1 - 2333:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterPolicyStmt")]
    internal sealed class AlterPolicyStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterPolicyStmt; }
        }

        public string policy_name { get; set; }

        public RangeVar table { get; set; }

        public IPg10Node[] roles { get; set; }

        public IPg10Node qual { get; set; }

        public IPg10Node with_check { get; set; }
    }
}
