/* Generated by QSI

 Date: 2020-08-12
 Span: 1795:1 - 1799:21
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterCollationStmt")]
    internal class AlterCollationStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterCollationStmt;

        public IPg10Node[] collname { get; set; }
    }
}
