/* Generated by QSI

 Date: 2020-08-07
 Span: 2207:1 - 2213:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterFdwStmt")]
    internal sealed class AlterFdwStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterFdwStmt; }
        }

        public string fdwname { get; set; }

        public IPg10Node[] func_options { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
