/* Generated by QSI

 Date: 2020-08-07
 Span: 2146:1 - 2152:29
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterTableSpaceOptionsStmt")]
    internal sealed class AlterTableSpaceOptionsStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterTableSpaceOptionsStmt; }
        }

        public string tablespacename { get; set; }

        public IPg10Node[] options { get; set; }

        public bool isReset { get; set; }
    }
}
