/* Generated by QSI

 Date: 2020-08-07
 Span: 1795:1 - 1799:21
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterCollationStmt")]
    internal sealed class AlterCollationStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterCollationStmt; }
        }

        public IPg10Node[] collname { get; set; }
    }
}
