/* Generated by QSI

 Date: 2020-08-07
 Span: 2178:1 - 2183:21
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterExtensionStmt")]
    internal sealed class AlterExtensionStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterExtensionStmt; }
        }

        public string extname { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
