/* Generated by QSI

 Date: 2020-08-07
 Span: 2817:1 - 2824:25
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterObjectDependsStmt")]
    internal sealed class AlterObjectDependsStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterObjectDependsStmt; }
        }

        public ObjectType objectType { get; set; }

        public RangeVar relation { get; set; }

        public IPg10Node @object { get; set; }

        public Value extname { get; set; }
    }
}
