/* Generated by QSI

 Date: 2020-08-07
 Span: 2439:1 - 2445:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterRoleStmt")]
    internal sealed class AlterRoleStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterRoleStmt; }
        }

        public RoleSpec role { get; set; }

        public IPg10Node[] options { get; set; }

        public int action { get; set; }
    }
}
