/* Generated by QSI

 Date: 2020-08-12
 Span: 3041:1 - 3046:23
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterDatabaseSetStmt")]
    internal class AlterDatabaseSetStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterDatabaseSetStmt;

        public string dbname { get; set; }

        public VariableSetStmt setstmt { get; set; }
    }
}
