/* Generated by QSI

 Date: 2020-08-12
 Span: 2154:1 - 2162:24
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterTableMoveAllStmt")]
    internal class AlterTableMoveAllStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterTableMoveAllStmt;

        public string orig_tablespacename { get; set; }

        public ObjectType? objtype { get; set; }

        public IPg10Node[] roles { get; set; }

        public string new_tablespacename { get; set; }

        public bool? nowait { get; set; }
    }
}
