/* Generated by QSI

 Date: 2020-08-07
 Span: 787:1 - 793:26
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlternativeSubPlanState")]
    internal sealed class AlternativeSubPlanState : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlternativeSubPlanState; }
        }

        public AlternativeSubPlan subplan { get; set; }

        public IPg10Node[] subplans { get; set; }

        public int active { get; set; }
    }
}
