/* Generated by QSI

 Date: 2020-08-12
 Span: 2146:1 - 2152:29
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterTableSpaceOptionsStmt")]
    internal class AlterTableSpaceOptionsStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterTableSpaceOptionsStmt;

        public string tablespacename { get; set; }

        public IPg10Node[] options { get; set; }

        public bool? isReset { get; set; }
    }
}
