/* Generated by QSI

 Date: 2020-08-07
 Span: 3408:1 - 3415:24
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum AlterSubscriptionType
    {
        ALTER_SUBSCRIPTION_OPTIONS = 0,
        ALTER_SUBSCRIPTION_CONNECTION = 1,
        ALTER_SUBSCRIPTION_PUBLICATION = 2,
        ALTER_SUBSCRIPTION_REFRESH = 3,
        ALTER_SUBSCRIPTION_ENABLED = 4
    }
}
