/* Generated by QSI

 Date: 2020-08-12
 Span: 3385:1 - 3397:23
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterPublicationStmt")]
    internal class AlterPublicationStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterPublicationStmt;

        public string pubname { get; set; }

        public IPg10Node[] options { get; set; }

        public IPg10Node[] tables { get; set; }

        public bool? for_all_tables { get; set; }

        public DefElemAction? tableAction { get; set; }
    }
}
