/* Generated by QSI

 Date: 2020-08-12
 Span: 3034:1 - 3039:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterDatabaseStmt")]
    internal class AlterDatabaseStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterDatabaseStmt;

        public string dbname { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
