/* Generated by QSI

 Date: 2020-08-07
 Span: 3034:1 - 3039:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterDatabaseStmt")]
    internal sealed class AlterDatabaseStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterDatabaseStmt; }
        }

        public string dbname { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
