/* Generated by QSI

 Date: 2020-08-07
 Span: 2231:1 - 2238:25
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterForeignServerStmt")]
    internal sealed class AlterForeignServerStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterForeignServerStmt; }
        }

        public string servername { get; set; }

        public string version { get; set; }

        public IPg10Node[] options { get; set; }

        public bool has_version { get; set; }
    }
}
