/* Generated by QSI

 Date: 2020-08-07
 Span: 3339:1 - 3344:24
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterTSDictionaryStmt")]
    internal sealed class AlterTSDictionaryStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterTSDictionaryStmt; }
        }

        public IPg10Node[] dictname { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
