/* Generated by QSI

 Date: 2020-08-12
 Span: 787:1 - 793:26
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlternativeSubPlanState")]
    internal class AlternativeSubPlanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlternativeSubPlanState;

        public AlternativeSubPlan subplan { get; set; }

        public IPg10Node[] subplans { get; set; }

        public int? active { get; set; }
    }
}
