/* Generated by QSI

 Date: 2020-08-12
 Span: 1809:1 - 1825:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterDomainStmt")]
    internal class AlterDomainStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterDomainStmt;

        public char? subtype { get; set; }

        public IPg10Node[] typeName { get; set; }

        public string name { get; set; }

        public IPg10Node[] def { get; set; }

        public DropBehavior? behavior { get; set; }

        public bool? missing_ok { get; set; }
    }
}
