/* Generated by QSI

 Date: 2020-08-07
 Span: 724:1 - 728:21
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class AlternativeSubPlan
    {
        public Expr xpr { get; set; }

        public IPg10Node[] subplans { get; set; }
    }
}
