/* Generated by QSI

 Date: 2020-08-07
 Span: 2858:1 - 2863:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterOperatorStmt")]
    internal sealed class AlterOperatorStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterOperatorStmt; }
        }

        public ObjectWithArgs opername { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
