/* Generated by QSI

 Date: 2020-08-07
 Span: 2561:1 - 2568:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterOpFamilyStmt")]
    internal class AlterOpFamilyStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterOpFamilyStmt;

        public NodeTag? type { get; set; }

        public IPg10Node[] opfamilyname { get; set; }

        public string amname { get; set; }

        public bool? isDrop { get; set; }

        public IPg10Node[] items { get; set; }
    }
}
