/* Generated by QSI

 Date: 2020-08-07
 Span: 1924:1 - 1929:29
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterDefaultPrivilegesStmt")]
    internal class AlterDefaultPrivilegesStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AlterDefaultPrivilegesStmt;

        public NodeTag? type { get; set; }

        public IPg10Node[] options { get; set; }

        public GrantStmt action { get; set; }
    }
}
