/* Generated by QSI

 Date: 2020-08-07
 Span: 2768:1 - 2773:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AlterFunctionStmt")]
    internal sealed class AlterFunctionStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_AlterFunctionStmt; }
        }

        public ObjectWithArgs func { get; set; }

        public IPg10Node[] actions { get; set; }
    }
}
