/* Generated by QSI

 Date: 2020-08-07
 Span: 245:1 - 251:9
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Append
    {
        public Plan plan { get; set; }

        public IPg10Node[] partitioned_rels { get; set; }

        public IPg10Node[] appendplans { get; set; }
    }
}
