/* Generated by QSI

 Date: 2020-08-12
 Span: 245:1 - 251:9
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Append")]
    internal class Append : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Append;

        public Plan plan { get; set; }

        public IPg10Node[] partitioned_rels { get; set; }

        public IPg10Node[] appendplans { get; set; }
    }
}
