/* Generated by QSI

 Date: 2020-08-07
 Span: 1980:1 - 2026:16
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("AppendRelInfo")]
    internal class AppendRelInfo : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_AppendRelInfo;

        public NodeTag? type { get; set; }

        public uint? parent_relid { get; set; }

        public uint? child_relid { get; set; }

        public uint? parent_reltype { get; set; }

        public uint? child_reltype { get; set; }

        public IPg10Node[] translated_vars { get; set; }

        public uint? parent_reloid { get; set; }
    }
}
