/* Generated by QSI

 Date: 2020-08-07
 Span: 396:1 - 412:11
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ArrayRef
    {
        public Expr xpr { get; set; }

        public uint refarraytype { get; set; }

        public uint refelemtype { get; set; }

        public int reftypmod { get; set; }

        public uint refcollid { get; set; }

        public IPg10Node[] refupperindexpr { get; set; }

        public IPg10Node[] reflowerindexpr { get; set; }

        public Expr refexpr { get; set; }

        public Expr refassgnexpr { get; set; }
    }
}
