/* Generated by QSI

 Date: 2020-08-12
 Span: 396:1 - 412:11
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ArrayRef")]
    internal class ArrayRef : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ArrayRef;

        public IPg10ExpressionNode xpr { get; set; }

        public uint? refarraytype { get; set; }

        public uint? refelemtype { get; set; }

        public int? reftypmod { get; set; }

        public uint? refcollid { get; set; }

        public IPg10Node[] refupperindexpr { get; set; }

        public IPg10Node[] reflowerindexpr { get; set; }

        public IPg10ExpressionNode refexpr { get; set; }

        public IPg10ExpressionNode refassgnexpr { get; set; }
    }
}
