/* Generated by QSI

 Date: 2020-08-07
 Span: 831:1 - 842:18
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ArrayCoerceExpr
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public uint elemfuncid { get; set; }

        public uint resulttype { get; set; }

        public int resulttypmod { get; set; }

        public uint resultcollid { get; set; }

        public bool isExplicit { get; set; }

        public CoercionForm coerceformat { get; set; }

        public int location { get; set; }
    }
}
