/* Generated by QSI

 Date: 2020-08-07
 Span: 949:1 - 958:12
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ArrayExpr
    {
        public Expr xpr { get; set; }

        public uint array_typeid { get; set; }

        public uint array_collid { get; set; }

        public uint element_typeid { get; set; }

        public IPg10Node[] elements { get; set; }

        public bool multidims { get; set; }

        public int location { get; set; }
    }
}
