/* Generated by QSI

 Date: 2020-08-12
 Span: 831:1 - 842:18
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ArrayCoerceExpr")]
    internal class ArrayCoerceExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ArrayCoerceExpr;

        public IPg10ExpressionNode xpr { get; set; }

        public IPg10ExpressionNode arg { get; set; }

        public uint? elemfuncid { get; set; }

        public uint? resulttype { get; set; }

        public int? resulttypmod { get; set; }

        public uint? resultcollid { get; set; }

        public bool? isExplicit { get; set; }

        public CoercionForm? coerceformat { get; set; }
    }
}
