/* Generated by QSI

 Date: 2020-08-07
 Span: 22:9 - 26:2
 File: src/postgres/include/access/tupdesc.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class attrDefault
    {
        public short adnum { get; set; }

        public string adbin { get; set; }
    }
}
