/* Generated by QSI

 Date: 2020-08-12
 Span: 1038:2 - 1038:19
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class binaryheap
    {
    }
}
