/* Generated by QSI

 Date: 2020-08-07
 Span: 18:1 - 18:17
 File: src/postgres/include/nodes/params.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Bitmapset
    {
        public int nwords { get; set; }

        public uint words { get; set; }
    }
}
