/* Generated by QSI

 Date: 2020-08-07
 Span: 442:1 - 449:18
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class BitmapIndexScan
    {
        public Scan scan { get; set; }

        public uint indexid { get; set; }

        public bool isshared { get; set; }

        public IPg10Node[] indexqual { get; set; }

        public IPg10Node[] indexqualorig { get; set; }
    }
}
