/* Generated by QSI

 Date: 2020-08-07
 Span: 300:1 - 304:12
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class BitmapAnd
    {
        public Plan plan { get; set; }

        public IPg10Node[] bitmapplans { get; set; }
    }
}
