/* Generated by QSI

 Date: 2020-08-07
 Span: 314:1 - 319:11
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class BitmapOr
    {
        public Plan plan { get; set; }

        public bool isshared { get; set; }

        public IPg10Node[] bitmapplans { get; set; }
    }
}
