/* Generated by QSI

 Date: 2020-08-07
 Span: 1274:1 - 1288:23
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("BitmapIndexScanState")]
    internal class BitmapIndexScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_BitmapIndexScanState;

        public ScanState ss { get; set; }

        public TIDBitmap biss_result { get; set; }

        public ScanKeyData biss_ScanKeys { get; set; }

        public int? biss_NumScanKeys { get; set; }

        public IndexRuntimeKeyInfo biss_RuntimeKeys { get; set; }

        public int? biss_NumRuntimeKeys { get; set; }

        public IndexArrayKeyInfo biss_ArrayKeys { get; set; }

        public int? biss_NumArrayKeys { get; set; }

        public bool? biss_RuntimeKeysReady { get; set; }

        public ExprContext biss_RuntimeContext { get; set; }

        public RelationData biss_RelationDesc { get; set; }

        public IndexScanDescData biss_ScanDesc { get; set; }
    }
}
