/* Generated by QSI

 Date: 2020-08-07
 Span: 460:1 - 464:17
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class BitmapHeapScan
    {
        public Scan scan { get; set; }

        public IPg10Node[] bitmapqualorig { get; set; }
    }
}
