/* Generated by QSI

 Date: 2020-08-07
 Span: 1355:1 - 1373:22
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("BitmapHeapScanState")]
    internal class BitmapHeapScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_BitmapHeapScanState;

        public ScanState ss { get; set; }

        public ExprState bitmapqualorig { get; set; }

        public TIDBitmap tbm { get; set; }

        public TBMIterator tbmiterator { get; set; }

        public TBMIterateResult tbmres { get; set; }

        public int? exact_pages { get; set; }

        public int? lossy_pages { get; set; }

        public TBMIterator prefetch_iterator { get; set; }

        public int? prefetch_pages { get; set; }

        public int? prefetch_target { get; set; }

        public int? prefetch_maximum { get; set; }

        public uint? pscan_len { get; set; }

        public bool? initialized { get; set; }

        public TBMSharedIterator shared_tbmiterator { get; set; }

        public TBMSharedIterator shared_prefetch_iterator { get; set; }

        public ParallelBitmapHeapState pstate { get; set; }
    }
}
