/* Generated by QSI

 Date: 2020-08-07
 Span: 1071:1 - 1076:16
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("BitmapAndPath")]
    internal class BitmapAndPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_BitmapAndPath;

        public Path path { get; set; }

        public IPg10Node[] bitmapquals { get; set; }

        public double? bitmapselectivity { get; set; }
    }
}
