/* Generated by QSI

 Date: 2020-08-12
 Span: 300:1 - 304:12
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("BitmapAnd")]
    internal class BitmapAnd : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_BitmapAnd;

        public Plan plan { get; set; }

        public IPg10Node[] bitmapplans { get; set; }
    }
}
