/* Generated by QSI

 Date: 2020-08-12
 Span: 460:1 - 464:17
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("BitmapHeapScan")]
    internal class BitmapHeapScan : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_BitmapHeapScan;

        public Scan scan { get; set; }

        public IPg10Node[] bitmapqualorig { get; set; }
    }
}
