/* Generated by QSI

 Date: 2020-08-12
 Span: 442:1 - 449:18
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("BitmapIndexScan")]
    internal class BitmapIndexScan : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_BitmapIndexScan;

        public Scan scan { get; set; }

        public uint? indexid { get; set; }

        public bool? isshared { get; set; }

        public IPg10Node[] indexqual { get; set; }

        public IPg10Node[] indexqualorig { get; set; }
    }
}
