/* Generated by QSI

 Date: 2020-08-07
 Span: 1200:1 - 1206:14
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class BooleanTest
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public BoolTestType booltesttype { get; set; }

        public int location { get; set; }
    }
}
