/* Generated by QSI

 Date: 2020-08-12
 Span: 559:1 - 565:11
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("BoolExpr")]
    internal class BoolExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_BoolExpr;

        public IPg10ExpressionNode xpr { get; set; }

        public BoolExprType? boolop { get; set; }

        public IPg10Node[] args { get; set; }
    }
}
