/* Generated by QSI

 Date: 2020-08-07
 Span: 554:1 - 557:15
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum BoolExprType
    {
        AND_EXPR = 0,
        OR_EXPR = 1,
        NOT_EXPR = 2
    }
}
