/* Generated by QSI

 Date: 2020-08-07
 Span: 559:1 - 565:11
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class BoolExpr
    {
        public Expr xpr { get; set; }

        public BoolExprType boolop { get; set; }

        public IPg10Node[] args { get; set; }

        public int location { get; set; }
    }
}
