/* Generated by QSI

 Date: 2020-08-12
 Span: 1195:1 - 1198:15
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum BoolTestType
    {
        IS_TRUE = 0,
        IS_NOT_TRUE = 1,
        IS_FALSE = 2,
        IS_NOT_FALSE = 3,
        IS_UNKNOWN = 4,
        IS_NOT_UNKNOWN = 5
    }
}
