/* Generated by QSI

 Date: 2020-08-07
 Span: 917:1 - 923:11
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CaseWhen")]
    internal class CaseWhen : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CaseWhen;

        public Expr xpr { get; set; }

        public Expr expr { get; set; }

        public Expr result { get; set; }
    }
}
