/* Generated by QSI

 Date: 2020-08-07
 Span: 933:1 - 939:15
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CaseTestExpr
    {
        public Expr xpr { get; set; }

        public uint typeId { get; set; }

        public int typeMod { get; set; }

        public uint collation { get; set; }
    }
}
