/* Generated by QSI

 Date: 2020-08-12
 Span: 917:1 - 923:11
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CaseWhen")]
    internal class CaseWhen : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CaseWhen;

        public IPg10ExpressionNode xpr { get; set; }

        public IPg10ExpressionNode expr { get; set; }

        public IPg10ExpressionNode result { get; set; }
    }
}
