/* Generated by QSI

 Date: 2020-08-07
 Span: 917:1 - 923:11
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CaseWhen
    {
        public Expr xpr { get; set; }

        public Expr expr { get; set; }

        public Expr result { get; set; }

        public int location { get; set; }
    }
}
