/* Generated by QSI

 Date: 2020-08-12
 Span: 3163:1 - 3166:17
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CheckPointStmt")]
    internal class CheckPointStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CheckPointStmt;
    }
}
