/* Generated by QSI

 Date: 2020-08-07
 Span: 3163:1 - 3166:17
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CheckPointStmt")]
    internal sealed class CheckPointStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_CheckPointStmt; }
        }
    }
}
