/* Generated by QSI

 Date: 2020-08-12
 Span: 2653:1 - 2658:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ClosePortalStmt")]
    internal class ClosePortalStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ClosePortalStmt;

        public string portalname { get; set; }
    }
}
