/* Generated by QSI

 Date: 2020-08-12
 Span: 649:1 - 660:10
 File: src/postgres/include/nodes/nodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum CmdType
    {
        CMD_UNKNOWN = 0,
        CMD_SELECT = 1,
        CMD_UPDATE = 2,
        CMD_INSERT = 3,
        CMD_DELETE = 4,
        CMD_UTILITY = 5,
        CMD_NOTHING = 6
    }
}
