/* Generated by QSI

 Date: 2020-08-12
 Span: 1042:1 - 1049:15
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CoalesceExpr")]
    internal class CoalesceExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CoalesceExpr;

        public IPg10Node xpr { get; set; }

        public uint? coalescetype { get; set; }

        public uint? coalescecollid { get; set; }

        public IPg10Node[] args { get; set; }
    }
}
