/* Generated by QSI

 Date: 2020-08-07
 Span: 1042:1 - 1049:15
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CoalesceExpr
    {
        public Expr xpr { get; set; }

        public uint coalescetype { get; set; }

        public uint coalescecollid { get; set; }

        public IPg10Node[] args { get; set; }

        public int location { get; set; }
    }
}
