/* Generated by QSI

 Date: 2020-08-07
 Span: 420:1 - 425:18
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum CoercionContext
    {
        COERCION_IMPLICIT = 0,
        COERCION_ASSIGNMENT = 1,
        COERCION_EXPLICIT = 2
    }
}
