/* Generated by QSI

 Date: 2020-08-07
 Span: 808:1 - 817:14
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CoerceViaIO
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public uint resulttype { get; set; }

        public uint resultcollid { get; set; }

        public CoercionForm coerceformat { get; set; }

        public int location { get; set; }
    }
}
