/* Generated by QSI

 Date: 2020-08-07
 Span: 436:1 - 441:15
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum CoercionForm
    {
        COERCE_EXPLICIT_CALL = 0,
        COERCE_EXPLICIT_CAST = 1,
        COERCE_IMPLICIT_CAST = 2
    }
}
