/* Generated by QSI

 Date: 2020-08-07
 Span: 873:1 - 879:14
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CollateExpr
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public uint collOid { get; set; }

        public int location { get; set; }
    }
}
