/* Generated by QSI

 Date: 2020-08-07
 Span: 305:1 - 311:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CollateClause")]
    internal class CollateClause : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CollateClause;

        public NodeTag? type { get; set; }

        public IPg10Node arg { get; set; }

        public IPg10Node[] collname { get; set; }
    }
}
