/* Generated by QSI

 Date: 2020-08-07
 Span: 305:1 - 311:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CollateClause")]
    internal sealed class CollateClause : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_CollateClause; }
        }

        public IPg10Node arg { get; set; }

        public IPg10Node[] collname { get; set; }

        public int location { get; set; }
    }
}
