/* Generated by QSI

 Date: 2020-08-07
 Span: 231:1 - 236:12
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ColumnRef")]
    internal sealed class ColumnRef : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_ColumnRef; }
        }

        public IPg10Node[] fields { get; set; }

        public int location { get; set; }
    }
}
