/* Generated by QSI

 Date: 2020-08-12
 Span: 1367:1 - 1383:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CommonTableExpr")]
    internal class CommonTableExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CommonTableExpr;

        public string ctename { get; set; }

        public IPg10Node[] aliascolnames { get; set; }

        public IPg10Node ctequery { get; set; }

        public bool? cterecursive { get; set; }

        public int? cterefcount { get; set; }

        public IPg10Node[] ctecolnames { get; set; }

        public IPg10Node[] ctecoltypes { get; set; }

        public IPg10Node[] ctecoltypmods { get; set; }

        public IPg10Node[] ctecolcollations { get; set; }
    }
}
