/* Generated by QSI

 Date: 2020-08-07
 Span: 2943:1 - 2948:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CompositeTypeStmt")]
    internal sealed class CompositeTypeStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_CompositeTypeStmt; }
        }

        public RangeVar typevar { get; set; }

        public IPg10Node[] coldeflist { get; set; }
    }
}
