/* Generated by QSI

 Date: 2020-08-12
 Span: 28:9 - 34:2
 File: src/postgres/include/access/tupdesc.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class constrCheck
    {
        public string ccname { get; set; }

        public string ccbin { get; set; }

        public bool? ccvalid { get; set; }

        public bool? ccnoinherit { get; set; }
    }
}
