/* Generated by QSI

 Date: 2020-08-12
 Span: 3203:1 - 3208:21
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ConstraintsSetStmt")]
    internal class ConstraintsSetStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ConstraintsSetStmt;

        public IPg10Node[] constraints { get; set; }

        public bool? deferred { get; set; }
    }
}
