/* Generated by QSI

 Date: 2020-08-07
 Span: 2048:1 - 2064:13
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum ConstrType
    {
        CONSTR_NULL = 0,
        CONSTR_NOTNULL = 1,
        CONSTR_DEFAULT = 2,
        CONSTR_IDENTITY = 3,
        CONSTR_CHECK = 4,
        CONSTR_PRIMARY = 5,
        CONSTR_UNIQUE = 6,
        CONSTR_EXCLUSION = 7,
        CONSTR_FOREIGN = 8,
        CONSTR_ATTR_DEFERRABLE = 9,
        CONSTR_ATTR_NOT_DEFERRABLE = 10,
        CONSTR_ATTR_DEFERRED = 11,
        CONSTR_ATTR_IMMEDIATE = 12
    }
}
