/* Generated by QSI

 Date: 2020-08-12
 Span: 2078:1 - 2123:13
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Constraint")]
    internal class Constraint : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Constraint;

        public ConstrType? contype { get; set; }

        public string conname { get; set; }

        public bool? deferrable { get; set; }

        public bool? initdeferred { get; set; }

        public bool? is_no_inherit { get; set; }

        public IPg10Node raw_expr { get; set; }

        public string cooked_expr { get; set; }

        public char? generated_when { get; set; }

        public IPg10Node[] keys { get; set; }

        public IPg10Node[] exclusions { get; set; }

        public IPg10Node[] options { get; set; }

        public string indexname { get; set; }

        public string indexspace { get; set; }

        public string access_method { get; set; }

        public IPg10Node where_clause { get; set; }

        public RangeVar pktable { get; set; }

        public IPg10Node[] fk_attrs { get; set; }

        public IPg10Node[] pk_attrs { get; set; }

        public char? fk_matchtype { get; set; }

        public char? fk_upd_action { get; set; }

        public char? fk_del_action { get; set; }

        public IPg10Node[] old_conpfeqop { get; set; }

        public uint? old_pktable_oid { get; set; }

        public bool? skip_validation { get; set; }

        public bool? initially_valid { get; set; }
    }
}
