/* Generated by QSI

 Date: 2020-08-07
 Span: 856:1 - 864:21
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ConvertRowtypeExpr
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public uint resulttype { get; set; }

        public CoercionForm convertformat { get; set; }

        public int location { get; set; }
    }
}
