/* Generated by QSI

 Date: 2020-08-12
 Span: 1671:1 - 1678:19
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateSchemaStmt")]
    internal class CreateSchemaStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateSchemaStmt;

        public string schemaname { get; set; }

        public RoleSpec authrole { get; set; }

        public IPg10Node[] schemaElts { get; set; }

        public bool? if_not_exists { get; set; }
    }
}
