/* Generated by QSI

 Date: 2020-08-07
 Span: 3269:1 - 3277:22
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateTransformStmt")]
    internal sealed class CreateTransformStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_CreateTransformStmt; }
        }

        public bool replace { get; set; }

        public TypeName type_name { get; set; }

        public string lang { get; set; }

        public ObjectWithArgs fromsql { get; set; }

        public ObjectWithArgs tosql { get; set; }
    }
}
