/* Generated by QSI

 Date: 2020-08-12
 Span: 2550:1 - 2555:21
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateOpFamilyStmt")]
    internal class CreateOpFamilyStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateOpFamilyStmt;

        public IPg10Node[] opfamilyname { get; set; }

        public string amname { get; set; }
    }
}
