/* Generated by QSI

 Date: 2020-08-12
 Span: 3137:1 - 3145:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateTableAsStmt")]
    internal class CreateTableAsStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateTableAsStmt;

        public IPg10Node query { get; set; }

        public IntoClause into { get; set; }

        public ObjectType? relkind { get; set; }

        public bool? is_select_into { get; set; }

        public bool? if_not_exists { get; set; }
    }
}
