/* Generated by QSI

 Date: 2020-08-12
 Span: 2351:1 - 2372:17
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateTrigStmt")]
    internal class CreateTrigStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateTrigStmt;

        public string trigname { get; set; }

        public RangeVar[] relation { get; set; }

        public IPg10Node[] funcname { get; set; }

        public IPg10Node[] args { get; set; }

        public bool? row { get; set; }

        public short? timing { get; set; }

        public short? events { get; set; }

        public IPg10Node[] columns { get; set; }

        public IPg10Node[] whenClause { get; set; }

        public bool? isconstraint { get; set; }

        public IPg10Node[] transitionRels { get; set; }

        public bool? deferrable { get; set; }

        public bool? initdeferred { get; set; }

        public RangeVar[] constrrel { get; set; }
    }
}
