/* Generated by QSI

 Date: 2020-08-07
 Span: 3023:1 - 3028:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreatedbStmt")]
    internal class CreatedbStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreatedbStmt;

        public NodeTag? type { get; set; }

        public string dbname { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
