/* Generated by QSI

 Date: 2020-08-12
 Span: 2257:1 - 2264:24
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateUserMappingStmt")]
    internal class CreateUserMappingStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateUserMappingStmt;

        public RoleSpec[] user { get; set; }

        public string servername { get; set; }

        public bool? if_not_exists { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
