/* Generated by QSI

 Date: 2020-08-12
 Span: 2965:1 - 2970:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateRangeStmt")]
    internal class CreateRangeStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateRangeStmt;

        public IPg10Node[] typeName { get; set; }

        public IPg10Node[] @params { get; set; }
    }
}
