/* Generated by QSI

 Date: 2020-08-07
 Span: 2220:1 - 2229:26
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateForeignServerStmt")]
    internal class CreateForeignServerStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateForeignServerStmt;

        public NodeTag? type { get; set; }

        public string servername { get; set; }

        public string servertype { get; set; }

        public string version { get; set; }

        public string fdwname { get; set; }

        public bool? if_not_exists { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
