/* Generated by QSI

 Date: 2020-08-07
 Span: 2724:1 - 2732:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateStatsStmt")]
    internal class CreateStatsStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateStatsStmt;

        public NodeTag? type { get; set; }

        public IPg10Node[] defnames { get; set; }

        public IPg10Node[] stat_types { get; set; }

        public IPg10Node[] exprs { get; set; }

        public IPg10Node[] relations { get; set; }

        public bool? if_not_exists { get; set; }
    }
}
