/* Generated by QSI

 Date: 2020-08-07
 Span: 2339:1 - 2345:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateAmStmt")]
    internal sealed class CreateAmStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_CreateAmStmt; }
        }

        public string amname { get; set; }

        public IPg10Node[] handler_name { get; set; }

        public char amtype { get; set; }
    }
}
