/* Generated by QSI

 Date: 2020-08-07
 Span: 3399:1 - 3406:25
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateSubscriptionStmt")]
    internal sealed class CreateSubscriptionStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_CreateSubscriptionStmt; }
        }

        public string subname { get; set; }

        public string conninfo { get; set; }

        public IPg10Node[] publication { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
