/* Generated by QSI

 Date: 2020-08-12
 Span: 3255:1 - 3263:17
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateCastStmt")]
    internal class CreateCastStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateCastStmt;

        public TypeName[] sourcetype { get; set; }

        public TypeName[] targettype { get; set; }

        public ObjectWithArgs[] func { get; set; }

        public CoercionContext? context { get; set; }

        public bool? inout { get; set; }
    }
}
