/* Generated by QSI

 Date: 2020-08-07
 Span: 3241:1 - 3249:23
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateConversionStmt")]
    internal sealed class CreateConversionStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_CreateConversionStmt; }
        }

        public IPg10Node[] conversion_name { get; set; }

        public string for_encoding_name { get; set; }

        public string to_encoding_name { get; set; }

        public IPg10Node[] func_name { get; set; }

        public bool def { get; set; }
    }
}
