/* Generated by QSI

 Date: 2020-08-12
 Span: 2245:1 - 2250:25
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateForeignTableStmt")]
    internal class CreateForeignTableStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateForeignTableStmt;

        public CreateStmt @base { get; set; }

        public string servername { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
