/* Generated by QSI

 Date: 2020-08-07
 Span: 2169:1 - 2175:22
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateExtensionStmt")]
    internal sealed class CreateExtensionStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_CreateExtensionStmt; }
        }

        public string extname { get; set; }

        public bool if_not_exists { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
