/* Generated by QSI

 Date: 2020-08-12
 Span: 2431:1 - 2437:17
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreateRoleStmt")]
    internal class CreateRoleStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreateRoleStmt;

        public RoleStmtType? stmt_type { get; set; }

        public string role { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
