/* Generated by QSI

 Date: 2020-08-07
 Span: 3376:1 - 3383:24
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CreatePublicationStmt")]
    internal class CreatePublicationStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CreatePublicationStmt;

        public NodeTag? type { get; set; }

        public string pubname { get; set; }

        public IPg10Node[] options { get; set; }

        public IPg10Node[] tables { get; set; }

        public bool? for_all_tables { get; set; }
    }
}
