/* Generated by QSI

 Date: 2020-08-07
 Span: 536:1 - 541:10
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CteScan")]
    internal class CteScan : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CteScan;

        public Scan scan { get; set; }

        public int? ctePlanId { get; set; }

        public int? cteParam { get; set; }
    }
}
