/* Generated by QSI

 Date: 2020-08-12
 Span: 1501:1 - 1512:15
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("CteScanState")]
    internal class CteScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_CteScanState;

        public ScanState ss { get; set; }

        public int? eflags { get; set; }

        public int? readptr { get; set; }

        public PlanState[] cteplanstate { get; set; }

        public CteScanState[] leader { get; set; }

        public Tuplestorestate[] cte_table { get; set; }

        public bool? eof_cte { get; set; }
    }
}
