/* Generated by QSI

 Date: 2020-08-07
 Span: 1274:1 - 1280:16
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CurrentOfExpr
    {
        public Expr xpr { get; set; }

        public uint cvarno { get; set; }

        public string cursor_name { get; set; }

        public int cursor_param { get; set; }
    }
}
