/* Generated by QSI

 Date: 2020-08-07
 Span: 1575:1 - 1575:25
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CustomExecMethods
    {
    }
}
