/* Generated by QSI

 Date: 2020-08-07
 Span: 623:1 - 634:13
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CustomScan
    {
        public Scan scan { get; set; }

        public uint flags { get; set; }

        public IPg10Node[] custom_plans { get; set; }

        public IPg10Node[] custom_exprs { get; set; }

        public IPg10Node[] custom_private { get; set; }

        public IPg10Node[] custom_scan_tlist { get; set; }

        public Bitmapset custom_relids { get; set; }

        public CustomScanMethods methods { get; set; }
    }
}
