/* Generated by QSI

 Date: 2020-08-12
 Span: 88:1 - 99:22
 File: src/postgres/include/nodes/extensible.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class CustomPathMethods
    {
        public char? CustomName { get; set; }

        public string PlanCustomPath { get; set; }
    }
}
