/* Generated by QSI

 Date: 2020-08-07
 Span: 105:1 - 111:20
 File: src/postgres/include/nodes/extensible.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class CustomScanMethods
    {
        public char? CustomName { get; set; }

        public string CreateCustomScanState { get; set; }
    }
}
