/* Generated by QSI

 Date: 2020-08-07
 Span: 621:1 - 621:25
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CustomScanMethods
    {
    }
}
