/* Generated by QSI

 Date: 2020-08-07
 Span: 1577:1 - 1585:18
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class CustomScanState
    {
        public ScanState ss { get; set; }

        public uint flags { get; set; }

        public IPg10Node[] custom_ps { get; set; }

        public uint pscan_len { get; set; }

        public CustomExecMethods methods { get; set; }
    }
}
