/* Generated by QSI

 Date: 2020-08-12
 Span: 117:1 - 151:20
 File: src/postgres/include/nodes/extensible.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class CustomExecMethods
    {
        public char? CustomName { get; set; }

        public string BeginCustomScan { get; set; }

        public string ExecCustomScan { get; set; }

        public string EndCustomScan { get; set; }

        public string ReScanCustomScan { get; set; }

        public string MarkPosCustomScan { get; set; }

        public string RestrPosCustomScan { get; set; }

        public string EstimateDSMCustomScan { get; set; }

        public string InitializeDSMCustomScan { get; set; }

        public string ReInitializeDSMCustomScan { get; set; }

        public string InitializeWorkerCustomScan { get; set; }

        public string ShutdownCustomScan { get; set; }

        public string ExplainCustomScan { get; set; }
    }
}
