/* Generated by QSI

 Date: 2020-08-07
 Span: 3309:1 - 3314:17
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DeallocateStmt")]
    internal class DeallocateStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_DeallocateStmt;

        public NodeTag? type { get; set; }

        public string name { get; set; }
    }
}
