/* Generated by QSI

 Date: 2020-08-12
 Span: 710:1 - 716:16
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum DefElemAction
    {
        DEFELEM_UNSPEC = 0,
        DEFELEM_SET = 1,
        DEFELEM_ADD = 2,
        DEFELEM_DROP = 3
    }
}
