/* Generated by QSI

 Date: 2020-08-07
 Span: 718:1 - 726:10
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DefElem")]
    internal sealed class DefElem : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_DefElem; }
        }

        public string defnamespace { get; set; }

        public string defname { get; set; }

        public IPg10Node arg { get; set; }

        public DefElemAction defaction { get; set; }

        public int location { get; set; }
    }
}
