/* Generated by QSI

 Date: 2020-08-07
 Span: 1460:1 - 1468:13
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DeleteStmt")]
    internal sealed class DeleteStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_DeleteStmt; }
        }

        public RangeVar relation { get; set; }

        public IPg10Node[] usingClause { get; set; }

        public IPg10Node whereClause { get; set; }

        public IPg10Node[] returningList { get; set; }

        public WithClause withClause { get; set; }
    }
}
