/* Generated by QSI

 Date: 2020-08-12
 Span: 3173:1 - 3179:14
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum DiscardMode
    {
        DISCARD_ALL = 0,
        DISCARD_PLANS = 1,
        DISCARD_SEQUENCES = 2,
        DISCARD_TEMP = 3
    }
}
