/* Generated by QSI

 Date: 2020-08-07
 Span: 3181:1 - 3185:14
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DiscardStmt")]
    internal sealed class DiscardStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_DiscardStmt; }
        }

        public DiscardMode target { get; set; }
    }
}
