/* Generated by QSI

 Date: 2020-08-07
 Span: 516:1 - 516:28
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DistinctExpr")]
    internal class DistinctExpr : OpExpr
    {
        public override NodeTag Type => NodeTag.T_DistinctExpr;
    }
}
