/* Generated by QSI

 Date: 2020-08-12
 Span: 808:1 - 815:24
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DomainConstraintState")]
    internal class DomainConstraintState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_DomainConstraintState;

        public DomainConstraintType? constrainttype { get; set; }

        public string name { get; set; }

        public IPg10Node[] check_expr { get; set; }

        public ExprState[] check_exprstate { get; set; }
    }
}
