/* Generated by QSI

 Date: 2020-08-12
 Span: 802:1 - 806:23
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum DomainConstraintType
    {
        DOM_CONSTRAINT_NOTNULL = 0,
        DOM_CONSTRAINT_CHECK = 1
    }
}
