/* Generated by QSI

 Date: 2020-08-07
 Span: 808:1 - 815:24
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DomainConstraintState")]
    internal sealed class DomainConstraintState : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_DomainConstraintState; }
        }

        public DomainConstraintType constrainttype { get; set; }

        public string name { get; set; }

        public Expr check_expr { get; set; }

        public ExprState check_exprstate { get; set; }
    }
}
