/* Generated by QSI

 Date: 2020-08-07
 Span: 2781:1 - 2785:9
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DoStmt")]
    internal sealed class DoStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_DoStmt; }
        }

        public IPg10Node[] args { get; set; }
    }
}
