/* Generated by QSI

 Date: 2020-08-07
 Span: 2781:1 - 2785:9
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DoStmt")]
    internal class DoStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_DoStmt;

        public NodeTag? type { get; set; }

        public IPg10Node[] args { get; set; }
    }
}
