/* Generated by QSI

 Date: 2020-08-07
 Span: 3427:1 - 3433:23
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DropSubscriptionStmt")]
    internal sealed class DropSubscriptionStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_DropSubscriptionStmt; }
        }

        public string subname { get; set; }

        public bool missing_ok { get; set; }

        public DropBehavior behavior { get; set; }
    }
}
