/* Generated by QSI

 Date: 2020-08-12
 Span: 2455:1 - 2460:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DropRoleStmt")]
    internal class DropRoleStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_DropRoleStmt;

        public IPg10Node[] roles { get; set; }

        public bool? missing_ok { get; set; }
    }
}
