/* Generated by QSI

 Date: 2020-08-07
 Span: 2575:1 - 2583:11
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DropStmt")]
    internal sealed class DropStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_DropStmt; }
        }

        public IPg10Node[] objects { get; set; }

        public ObjectType removeType { get; set; }

        public DropBehavior behavior { get; set; }

        public bool missing_ok { get; set; }

        public bool concurrent { get; set; }
    }
}
