/* Generated by QSI

 Date: 2020-08-07
 Span: 3319:1 - 3324:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("DropOwnedStmt")]
    internal sealed class DropOwnedStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_DropOwnedStmt; }
        }

        public IPg10Node[] roles { get; set; }

        public DropBehavior behavior { get; set; }
    }
}
