/* Generated by QSI

 Date: 2020-08-12
 Span: 1680:1 - 1684:15
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum DropBehavior
    {
        DROP_RESTRICT = 0,
        DROP_CASCADE = 1
    }
}
