/* Generated by QSI

 Date: 2020-08-07
 Span: 22:1 - 22:33
 File: src/postgres/include/utils/dsa.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class dsa_area
    {
    }
}
