/* Generated by QSI

 Date: 2020-08-12
 Span: 914:1 - 922:11
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class EPQState
    {
        public EState estate { get; set; }

        public PlanState planstate { get; set; }

        public TupleTableSlot origslot { get; set; }

        public Plan plan { get; set; }

        public IPg10Node[] arowMarks { get; set; }

        public int? epqParam { get; set; }
    }
}
