/* Generated by QSI

 Date: 2020-08-12
 Span: 768:1 - 787:19
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("EquivalenceClass")]
    internal class EquivalenceClass : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_EquivalenceClass;

        public IPg10Node[] ec_opfamilies { get; set; }

        public uint? ec_collation { get; set; }

        public IPg10Node[] ec_members { get; set; }

        public IPg10Node[] ec_sources { get; set; }

        public IPg10Node[] ec_derives { get; set; }

        public Bitmapset ec_relids { get; set; }

        public bool? ec_has_const { get; set; }

        public bool? ec_has_volatile { get; set; }

        public bool? ec_below_outer_join { get; set; }

        public bool? ec_broken { get; set; }

        public uint? ec_sortref { get; set; }

        public uint? ec_min_security { get; set; }

        public uint? ec_max_security { get; set; }

        public EquivalenceClass ec_merged { get; set; }
    }
}
