/* Generated by QSI

 Date: 2020-08-12
 Span: 818:1 - 828:20
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("EquivalenceMember")]
    internal class EquivalenceMember : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_EquivalenceMember;

        public IPg10Node[] em_expr { get; set; }

        public Bitmapset[] em_relids { get; set; }

        public Bitmapset[] em_nullable_relids { get; set; }

        public bool? em_is_const { get; set; }

        public bool? em_is_child { get; set; }

        public uint? em_datatype { get; set; }
    }
}
