/* Generated by QSI

 Date: 2020-08-07
 Span: 23:1 - 29:19
 File: src/postgres/include/commands/event_trigger.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("EventTriggerData")]
    internal sealed class EventTriggerData : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_EventTriggerData; }
        }

        public char @event { get; set; }

        public IPg10Node parsetree { get; set; }

        public char tag { get; set; }
    }
}
