/* Generated by QSI

 Date: 2020-08-07
 Span: 3117:1 - 3122:14
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ExplainStmt")]
    internal sealed class ExplainStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_ExplainStmt; }
        }

        public IPg10Node query { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
