/* Generated by QSI

 Date: 2020-08-07
 Span: 53:1 - 97:12
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ExprState
    {
        public IPg10Node tag { get; set; }

        public byte flags { get; set; }

        public bool resnull { get; set; }

        public uint resvalue { get; set; }

        public TupleTableSlot resultslot { get; set; }

        public ExprEvalStep steps { get; set; }

        public string evalfunc { get; set; }

        public Expr expr { get; set; }

        public int steps_len { get; set; }

        public int steps_alloc { get; set; }

        public uint innermost_caseval { get; set; }

        public bool[] innermost_casenull { get; set; }

        public uint innermost_domainval { get; set; }

        public bool[] innermost_domainnull { get; set; }
    }
}
