/* Generated by QSI

 Date: 2020-08-12
 Span: 162:1 - 167:17
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class ExprContext_CB
    {
        public ExprContext_CB[] next { get; set; }

        public string[] function { get; set; }

        public uint? arg { get; set; }
    }
}
