/* Generated by QSI

 Date: 2020-08-07
 Span: 235:1 - 240:15
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum ExprDoneCond
    {
        ExprSingleResult = 0,
        ExprMultipleResult = 1,
        ExprEndResult = 2
    }
}
