/* Generated by QSI

 Date: 2020-08-07
 Span: 43:1 - 43:20
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class ExprEvalStep
    {
    }
}
