/* Generated by QSI

 Date: 2020-08-07
 Span: 132:1 - 135:7
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Expr")]
    internal class Expr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Expr;

        public NodeTag? type { get; set; }
    }
}
