/* Generated by QSI

 Date: 2020-08-07
 Span: 132:1 - 135:7
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Expr")]
    internal sealed class Expr : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_Expr; }
        }
    }
}
