/* Generated by QSI

 Date: 2020-08-07
 Span: 378:2 - 378:19
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class FdwRoutine
    {
    }
}
