/* Generated by QSI

 Date: 2020-08-12
 Span: 378:2 - 378:19
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("FdwRoutine")]
    internal class FdwRoutine : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_FdwRoutine;
    }
}
