/* Generated by QSI

 Date: 2020-08-07
 Span: 2664:1 - 2672:17
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum FetchDirection
    {
        FETCH_FORWARD = 0,
        FETCH_BACKWARD = 1,
        FETCH_ABSOLUTE = 2,
        FETCH_RELATIVE = 3
    }
}
