/* Generated by QSI

 Date: 2020-08-07
 Span: 2676:1 - 2683:12
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("FetchStmt")]
    internal class FetchStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_FetchStmt;

        public NodeTag? type { get; set; }

        public FetchDirection? direction { get; set; }

        public int? howMany { get; set; }

        public string portalname { get; set; }

        public bool? ismove { get; set; }
    }
}
