/* Generated by QSI

 Date: 2020-08-07
 Span: 765:1 - 773:13
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class FieldStore
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public IPg10Node[] newvals { get; set; }

        public IPg10Node[] fieldnums { get; set; }

        public uint resulttype { get; set; }
    }
}
