/* Generated by QSI

 Date: 2020-08-12
 Span: 739:1 - 748:14
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("FieldSelect")]
    internal class FieldSelect : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_FieldSelect;

        public IPg10Node xpr { get; set; }

        public IPg10Node[] arg { get; set; }

        public short? fieldnum { get; set; }

        public uint? resulttype { get; set; }

        public int? resulttypmod { get; set; }

        public uint? resultcollid { get; set; }
    }
}
