/* Generated by QSI

 Date: 2020-08-07
 Span: 739:1 - 748:14
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class FieldSelect
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public short fieldnum { get; set; }

        public uint resulttype { get; set; }

        public int resulttypmod { get; set; }

        public uint resultcollid { get; set; }
    }
}
