/* Generated by QSI

 Date: 2020-08-12
 Span: 595:1 - 606:14
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ForeignScan")]
    internal class ForeignScan : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ForeignScan;

        public Scan scan { get; set; }

        public CmdType? operation { get; set; }

        public uint? fs_server { get; set; }

        public IPg10Node[] fdw_exprs { get; set; }

        public IPg10Node[] fdw_private { get; set; }

        public IPg10Node[] fdw_scan_tlist { get; set; }

        public IPg10Node[] fdw_recheck_quals { get; set; }

        public Bitmapset[] fs_relids { get; set; }

        public bool? fsSystemCol { get; set; }
    }
}
