/* Generated by QSI

 Date: 2020-08-12
 Span: 236:1 - 246:22
 File: src/postgres/include/utils/rel.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ForeignKeyCacheInfo")]
    internal class ForeignKeyCacheInfo : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ForeignKeyCacheInfo;

        public uint? conrelid { get; set; }

        public uint? confrelid { get; set; }

        public int? nkeys { get; set; }

        public short? conkey { get; set; }

        public short? confkey { get; set; }

        public uint? conpfeqop { get; set; }
    }
}
