/* Generated by QSI

 Date: 2020-08-12
 Span: 32:1 - 84:20
 File: src/postgres/include/catalog/pg_class.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class FormData_pg_class
    {
        public nameData relname { get; set; }

        public uint? relnamespace { get; set; }

        public uint? reltype { get; set; }

        public uint? reloftype { get; set; }

        public uint? relowner { get; set; }

        public uint? relam { get; set; }

        public uint? relfilenode { get; set; }

        public uint? reltablespace { get; set; }

        public int? relpages { get; set; }

        public float? reltuples { get; set; }

        public int? relallvisible { get; set; }

        public uint? reltoastrelid { get; set; }

        public bool? relhasindex { get; set; }

        public bool? relisshared { get; set; }

        public char? relpersistence { get; set; }

        public char? relkind { get; set; }

        public short? relnatts { get; set; }

        public short? relchecks { get; set; }

        public bool? relhasoids { get; set; }

        public bool? relhaspkey { get; set; }

        public bool? relhasrules { get; set; }

        public bool? relhastriggers { get; set; }

        public bool? relhassubclass { get; set; }

        public bool? relrowsecurity { get; set; }

        public bool? relforcerowsecurity { get; set; }

        public bool? relispopulated { get; set; }

        public char? relreplident { get; set; }

        public bool? relispartition { get; set; }

        public uint? relfrozenxid { get; set; }

        public uint? relminmxid { get; set; }
    }
}
