/* Generated by QSI

 Date: 2020-08-12
 Span: 1468:1 - 1473:11
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("FromExpr")]
    internal class FromExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_FromExpr;

        public IPg10Node[] fromlist { get; set; }

        public IPg10Node quals { get; set; }
    }
}
