/* Generated by QSI

 Date: 2020-08-07
 Span: 1428:1 - 1438:20
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class FunctionScanState
    {
        public ScanState ss { get; set; }

        public int eflags { get; set; }

        public bool ordinality { get; set; }

        public bool simple { get; set; }

        public int ordinal { get; set; }

        public int nfuncs { get; set; }

        public FunctionScanPerFuncState funcstates { get; set; }

        public MemoryContextData[] argcontext { get; set; }
    }
}
