/* Generated by QSI

 Date: 2020-08-07
 Span: 2749:1 - 2757:24
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum FunctionParameterMode
    {
        FUNC_PARAM_IN = 105,
        FUNC_PARAM_OUT = 111,
        FUNC_PARAM_INOUT = 98,
        FUNC_PARAM_VARIADIC = 118,
        FUNC_PARAM_TABLE = 116
    }
}
