/* Generated by QSI

 Date: 2020-08-07
 Span: 505:1 - 510:15
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class FunctionScan
    {
        public Scan scan { get; set; }

        public IPg10Node[] functions { get; set; }

        public bool funcordinality { get; set; }
    }
}
