/* Generated by QSI

 Date: 2020-08-12
 Span: 446:1 - 459:11
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("FuncExpr")]
    internal class FuncExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_FuncExpr;

        public IPg10Node xpr { get; set; }

        public uint? funcid { get; set; }

        public uint? funcresulttype { get; set; }

        public bool? funcretset { get; set; }

        public bool? funcvariadic { get; set; }

        public CoercionForm? funcformat { get; set; }

        public uint? funccollid { get; set; }

        public uint? inputcollid { get; set; }

        public IPg10Node[] args { get; set; }
    }
}
