/* Generated by QSI

 Date: 2020-08-12
 Span: 346:1 - 359:11
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("FuncCall")]
    internal class FuncCall : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_FuncCall;

        public IPg10Node[] funcname { get; set; }

        public IPg10Node[] args { get; set; }

        public IPg10Node[] agg_order { get; set; }

        public IPg10Node[] agg_filter { get; set; }

        public bool? agg_within_group { get; set; }

        public bool? agg_star { get; set; }

        public bool? agg_distinct { get; set; }

        public bool? func_variadic { get; set; }

        public WindowDef[] over { get; set; }
    }
}
