/* Generated by QSI

 Date: 2020-08-07
 Span: 505:1 - 510:15
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("FunctionScan")]
    internal class FunctionScan : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_FunctionScan;

        public Scan scan { get; set; }

        public IPg10Node[] functions { get; set; }

        public bool? funcordinality { get; set; }
    }
}
