/* Generated by QSI

 Date: 2020-08-07
 Span: 2759:1 - 2766:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("FunctionParameter")]
    internal class FunctionParameter : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_FunctionParameter;

        public NodeTag? type { get; set; }

        public string name { get; set; }

        public TypeName argType { get; set; }

        public FunctionParameterMode? mode { get; set; }

        public IPg10Node defexpr { get; set; }
    }
}
