/* Generated by QSI

 Date: 2020-08-07
 Span: 2759:1 - 2766:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("FunctionParameter")]
    internal sealed class FunctionParameter : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_FunctionParameter; }
        }

        public string name { get; set; }

        public TypeName argType { get; set; }

        public FunctionParameterMode mode { get; set; }

        public IPg10Node defexpr { get; set; }
    }
}
