/* Generated by QSI

 Date: 2020-08-07
 Span: 1426:1 - 1426:32
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class FunctionScanPerFuncState
    {
    }
}
