/* Generated by QSI

 Date: 2020-08-07
 Span: 850:1 - 861:14
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class GatherMerge
    {
        public Plan plan { get; set; }

        public int num_workers { get; set; }

        public int rescan_param { get; set; }

        public int numCols { get; set; }

        public short sortColIdx { get; set; }

        public uint sortOperators { get; set; }

        public uint collations { get; set; }

        public bool[] nullsFirst { get; set; }
    }
}
