/* Generated by QSI

 Date: 2020-08-07
 Span: 837:1 - 844:9
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Gather
    {
        public Plan plan { get; set; }

        public int num_workers { get; set; }

        public int rescan_param { get; set; }

        public bool single_copy { get; set; }

        public bool invisible { get; set; }
    }
}
