/* Generated by QSI

 Date: 2020-08-07
 Span: 1948:1 - 1967:19
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class GatherMergeState
    {
        public PlanState ps { get; set; }

        public bool initialized { get; set; }

        public bool gm_initialized { get; set; }

        public bool need_to_scan_locally { get; set; }

        public tupleDesc tupDesc { get; set; }

        public int gm_nkeys { get; set; }

        public SortSupportData gm_sortkeys { get; set; }

        public ParallelExecutorInfo pei { get; set; }

        public int nworkers_launched { get; set; }

        public int nreaders { get; set; }

        public TupleTableSlot[] gm_slots { get; set; }

        public TupleQueueReader[] reader { get; set; }

        public GMReaderTupleBuffer gm_tuple_buffers { get; set; }

        public binaryheap gm_heap { get; set; }
    }
}
