/* Generated by QSI

 Date: 2020-08-07
 Span: 1262:1 - 1268:13
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("GatherPath")]
    internal class GatherPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_GatherPath;

        public Path path { get; set; }

        public Path subpath { get; set; }

        public bool? single_copy { get; set; }

        public int? num_workers { get; set; }
    }
}
