/* Generated by QSI

 Date: 2020-08-12
 Span: 837:1 - 844:9
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Gather")]
    internal class Gather : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Gather;

        public Plan plan { get; set; }

        public int? num_workers { get; set; }

        public int? rescan_param { get; set; }

        public bool? single_copy { get; set; }

        public bool? invisible { get; set; }
    }
}
