/* Generated by QSI

 Date: 2020-08-07
 Span: 1946:1 - 1946:27
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class GMReaderTupleBuffer
    {
    }
}
