/* Generated by QSI

 Date: 2020-08-07
 Span: 1856:1 - 1869:12
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("GrantStmt")]
    internal sealed class GrantStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_GrantStmt; }
        }

        public bool is_grant { get; set; }

        public GrantTargetType targtype { get; set; }

        public GrantObjectType objtype { get; set; }

        public IPg10Node[] objects { get; set; }

        public IPg10Node[] privileges { get; set; }

        public IPg10Node[] grantees { get; set; }

        public bool grant_option { get; set; }

        public DropBehavior behavior { get; set; }
    }
}
