/* Generated by QSI

 Date: 2020-08-07
 Span: 1839:1 - 1854:18
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum GrantObjectType
    {
        ACL_OBJECT_COLUMN = 0,
        ACL_OBJECT_RELATION = 1,
        ACL_OBJECT_SEQUENCE = 2,
        ACL_OBJECT_DATABASE = 3,
        ACL_OBJECT_DOMAIN = 4,
        ACL_OBJECT_FDW = 5,
        ACL_OBJECT_FOREIGN_SERVER = 6,
        ACL_OBJECT_FUNCTION = 7,
        ACL_OBJECT_LANGUAGE = 8,
        ACL_OBJECT_LARGEOBJECT = 9,
        ACL_OBJECT_NAMESPACE = 10,
        ACL_OBJECT_TABLESPACE = 11,
        ACL_OBJECT_TYPE = 12
    }
}
