/* Generated by QSI

 Date: 2020-08-07
 Span: 1832:1 - 1837:18
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum GrantTargetType
    {
        ACL_TARGET_OBJECT = 0,
        ACL_TARGET_ALL_IN_SCHEMA = 1,
        ACL_TARGET_DEFAULTS = 2
    }
}
