/* Generated by QSI

 Date: 2020-08-12
 Span: 758:1 - 764:8
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Group")]
    internal class Group : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Group;

        public Plan plan { get; set; }

        public int? numCols { get; set; }

        public short[] grpColIdx { get; set; }

        public uint[] grpOperators { get; set; }
    }
}
