/* Generated by QSI

 Date: 2020-08-12
 Span: 1494:1 - 1501:19
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("GroupingSetsPath")]
    internal class GroupingSetsPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_GroupingSetsPath;

        public Path path { get; set; }

        public Path[] subpath { get; set; }

        public AggStrategy? aggstrategy { get; set; }

        public IPg10Node[] rollups { get; set; }

        public IPg10Node[] qual { get; set; }
    }
}
