/* Generated by QSI

 Date: 2020-08-07
 Span: 1766:1 - 1771:13
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("GroupState")]
    internal class GroupState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_GroupState;

        public ScanState ss { get; set; }

        public FmgrInfo eqfunctions { get; set; }

        public bool? grp_done { get; set; }
    }
}
