/* Generated by QSI

 Date: 2020-08-07
 Span: 1766:1 - 1771:13
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class GroupState
    {
        public ScanState ss { get; set; }

        public FmgrInfo eqfunctions { get; set; }

        public bool grp_done { get; set; }
    }
}
