/* Generated by QSI

 Date: 2020-08-07
 Span: 1258:1 - 1264:14
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("GroupingSet")]
    internal class GroupingSet : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_GroupingSet;

        public NodeTag? type { get; set; }

        public GroupingSetKind? kind { get; set; }

        public IPg10Node[] content { get; set; }
    }
}
