/* Generated by QSI

 Date: 2020-08-07
 Span: 1472:1 - 1477:18
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("GroupingSetData")]
    internal class GroupingSetData : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_GroupingSetData;

        public NodeTag? type { get; set; }

        public IPg10Node[] set { get; set; }

        public double? numGroups { get; set; }
    }
}
