/* Generated by QSI

 Date: 2020-08-07
 Span: 758:1 - 764:8
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Group
    {
        public Plan plan { get; set; }

        public int numCols { get; set; }

        public short grpColIdx { get; set; }

        public uint grpOperators { get; set; }
    }
}
