/* Generated by QSI

 Date: 2020-08-07
 Span: 871:1 - 878:7
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Hash
    {
        public Plan plan { get; set; }

        public uint skewTable { get; set; }

        public short skewColumn { get; set; }

        public bool skewInherit { get; set; }
    }
}
