/* Generated by QSI

 Date: 2020-08-07
 Span: 1699:9 - 1699:33
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class HashJoinTableData
    {
    }
}
