/* Generated by QSI

 Date: 2020-08-07
 Span: 1973:1 - 1979:12
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class HashState
    {
        public PlanState ps { get; set; }

        public HashJoinTableData hashtable { get; set; }

        public IPg10Node[] hashkeys { get; set; }
    }
}
