/* Generated by QSI

 Date: 2020-08-07
 Span: 723:1 - 727:11
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class HashJoin
    {
        public Join join { get; set; }

        public IPg10Node[] hashclauses { get; set; }
    }
}
