/* Generated by QSI

 Date: 2020-08-07
 Span: 1368:1 - 1373:11
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("HashPath")]
    internal class HashPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_HashPath;

        public JoinPath jpath { get; set; }

        public IPg10Node[] path_hashclauses { get; set; }

        public int? num_batches { get; set; }
    }
}
