/* Generated by QSI

 Date: 2020-08-07
 Span: 1698:9 - 1698:33
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class HashJoinTupleData
    {
    }
}
