/* Generated by QSI

 Date: 2020-08-12
 Span: 871:1 - 878:7
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Hash")]
    internal class Hash : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Hash;

        public Plan plan { get; set; }

        public uint? skewTable { get; set; }

        public short? skewColumn { get; set; }

        public bool? skewInherit { get; set; }
    }
}
