/* Generated by QSI

 Date: 2020-08-07
 Span: 100:9 - 100:32
 File: src/postgres/include/access/heapam.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class HeapScanDescData
    {
    }
}
