/* Generated by QSI

 Date: 2020-08-07
 Span: 62:1 - 68:16
 File: src/postgres/include/access/htup.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class HeapTupleData
    {
        public uint? t_len { get; set; }

        public ItemPointerData t_self { get; set; }

        public uint? t_tableOid { get; set; }

        public HeapTupleHeaderData t_data { get; set; }
    }
}
