/* Generated by QSI

 Date: 2020-08-12
 Span: 21:1 - 21:55
 File: src/postgres/include/access/htup.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class HeapTupleHeaderData
    {
    }
}
