/* Generated by QSI

 Date: 2020-08-12
 Span: 2294:1 - 2303:26
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ImportForeignSchemaStmt")]
    internal class ImportForeignSchemaStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ImportForeignSchemaStmt;

        public string server_name { get; set; }

        public string remote_schema { get; set; }

        public string local_schema { get; set; }

        public ImportForeignSchemaType? list_type { get; set; }

        public IPg10Node[] table_list { get; set; }

        public IPg10Node[] options { get; set; }
    }
}
