/* Generated by QSI

 Date: 2020-08-12
 Span: 2287:1 - 2292:26
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum ImportForeignSchemaType
    {
        FDW_IMPORT_SCHEMA_ALL = 0,
        FDW_IMPORT_SCHEMA_LIMIT_TO = 1,
        FDW_IMPORT_SCHEMA_EXCEPT = 2
    }
}
