/* Generated by QSI

 Date: 2020-08-12
 Span: 181:2 - 181:23
 File: src/postgres/include/utils/rel.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("IndexAmRoutine")]
    internal class IndexAmRoutine : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_IndexAmRoutine;
    }
}
