/* Generated by QSI

 Date: 2020-08-12
 Span: 1193:1 - 1218:17
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("IndexScanState")]
    internal class IndexScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_IndexScanState;

        public ScanState ss { get; set; }

        public ExprState indexqualorig { get; set; }

        public IPg10Node[] indexorderbyorig { get; set; }

        public ScanKeyData iss_ScanKeys { get; set; }

        public int? iss_NumScanKeys { get; set; }

        public ScanKeyData iss_OrderByKeys { get; set; }

        public int? iss_NumOrderByKeys { get; set; }

        public IndexRuntimeKeyInfo iss_RuntimeKeys { get; set; }

        public int? iss_NumRuntimeKeys { get; set; }

        public bool? iss_RuntimeKeysReady { get; set; }

        public ExprContext iss_RuntimeContext { get; set; }

        public RelationData iss_RelationDesc { get; set; }

        public IndexScanDescData iss_ScanDesc { get; set; }

        public pairingheap iss_ReorderQueue { get; set; }

        public bool? iss_ReachedEnd { get; set; }

        public uint? iss_OrderByValues { get; set; }

        public bool?[] iss_OrderByNulls { get; set; }

        public SortSupportData iss_SortSupport { get; set; }

        public bool?[] iss_OrderByTypByVals { get; set; }

        public short? iss_OrderByTypLens { get; set; }

        public uint? iss_PscanLen { get; set; }
    }
}
