/* Generated by QSI

 Date: 2020-08-07
 Span: 386:1 - 396:12
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class IndexScan
    {
        public Scan scan { get; set; }

        public uint indexid { get; set; }

        public IPg10Node[] indexqual { get; set; }

        public IPg10Node[] indexqualorig { get; set; }

        public IPg10Node[] indexorderby { get; set; }

        public IPg10Node[] indexorderbyorig { get; set; }

        public IPg10Node[] indexorderbyops { get; set; }

        public ScanDirection indexorderdir { get; set; }
    }
}
