/* Generated by QSI

 Date: 2020-08-12
 Span: 86:9 - 86:33
 File: src/postgres/include/access/genam.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class IndexScanDescData
    {
    }
}
