/* Generated by QSI

 Date: 2020-08-12
 Span: 1028:1 - 1040:12
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("IndexPath")]
    internal class IndexPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_IndexPath;

        public Path path { get; set; }

        public IndexOptInfo indexinfo { get; set; }

        public IPg10Node[] indexclauses { get; set; }

        public IPg10Node[] indexquals { get; set; }

        public IPg10Node[] indexqualcols { get; set; }

        public IPg10Node[] indexorderbys { get; set; }

        public IPg10Node[] indexorderbycols { get; set; }

        public ScanDirection? indexscandir { get; set; }

        public double? indextotalcost { get; set; }

        public double? indexselectivity { get; set; }
    }
}
