/* Generated by QSI

 Date: 2020-08-12
 Span: 1150:1 - 1155:22
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class IndexRuntimeKeyInfo
    {
        public ScanKeyData scan_key { get; set; }

        public ExprState key_expr { get; set; }

        public bool? key_toastable { get; set; }
    }
}
