/* Generated by QSI

 Date: 2020-08-07
 Span: 131:1 - 152:12
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("IndexInfo")]
    internal class IndexInfo : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_IndexInfo;

        public NodeTag? type { get; set; }

        public int? ii_NumIndexAttrs { get; set; }

        public short? ii_KeyAttrNumbers { get; set; }

        public IPg10Node[] ii_Expressions { get; set; }

        public IPg10Node[] ii_ExpressionsState { get; set; }

        public IPg10Node[] ii_Predicate { get; set; }

        public ExprState ii_PredicateState { get; set; }

        public uint? ii_ExclusionOps { get; set; }

        public uint? ii_ExclusionProcs { get; set; }

        public ushort? ii_ExclusionStrats { get; set; }

        public uint? ii_UniqueOps { get; set; }

        public uint? ii_UniqueProcs { get; set; }

        public ushort? ii_UniqueStrats { get; set; }

        public bool? ii_Unique { get; set; }

        public bool? ii_ReadyForInserts { get; set; }

        public bool? ii_Concurrent { get; set; }

        public bool? ii_BrokenHotChain { get; set; }

        public object?[] ii_AmCache { get; set; }

        public MemoryContext ii_Context { get; set; }
    }
}
