/* Generated by QSI

 Date: 2020-08-07
 Span: 1336:1 - 1343:14
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("InferClause")]
    internal class InferClause : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_InferClause;

        public NodeTag? type { get; set; }

        public IPg10Node[] indexElems { get; set; }

        public IPg10Node whereClause { get; set; }

        public string conname { get; set; }
    }
}
