/* Generated by QSI

 Date: 2020-08-07
 Span: 1303:1 - 1309:16
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class InferenceElem
    {
        public Expr xpr { get; set; }

        public IPg10Node expr { get; set; }

        public uint infercollid { get; set; }

        public uint inferopclass { get; set; }
    }
}
