/* Generated by QSI

 Date: 2020-08-07
 Span: 545:1 - 554:13
 File: src/postgres/include/c.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class int2vector
    {
        public int? vl_len_ { get; set; }

        public int? ndim { get; set; }

        public int? dataoffset { get; set; }

        public uint? elemtype { get; set; }

        public int? dim1 { get; set; }

        public int? lbound1 { get; set; }

        public short? values { get; set; }
    }
}
