/* Generated by QSI

 Date: 2020-08-07
 Span: 105:1 - 116:13
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("IntoClause")]
    internal class IntoClause : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_IntoClause;

        public NodeTag? type { get; set; }

        public RangeVar rel { get; set; }

        public IPg10Node[] colNames { get; set; }

        public IPg10Node[] options { get; set; }

        public OnCommitAction? onCommit { get; set; }

        public string tableSpaceName { get; set; }

        public IPg10Node viewQuery { get; set; }

        public bool? skipData { get; set; }
    }
}
