/* Generated by QSI

 Date: 2020-08-12
 Span: 132:1 - 135:7
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal interface IPg10ExpressionNode : IPg10Node
    {
    }
}
