/* Generated by QSI

 Date: 2020-08-07
 Span: 509:1 - 512:7
 File: src/postgres/include/nodes/nodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal interface IPg10Node : IPgNode
    {
        NodeTag Type { get; }
    }
}
