/* Generated by QSI

 Date: 2020-08-07
 Span: 36:1 - 47:16
 File: src/postgres/include/storage/itemptr.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ItemPointerData
    {
        public BlockIdData ip_blkid { get; set; }

        public ushort ip_posid { get; set; }
    }
}
