/* Generated by QSI

 Date: 2020-08-07
 Span: 664:1 - 670:7
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Join")]
    internal class Join : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Join;

        public Plan plan { get; set; }

        public JoinType? jointype { get; set; }

        public bool? inner_unique { get; set; }

        public IPg10Node[] joinqual { get; set; }
    }
}
