/* Generated by QSI

 Date: 2020-08-12
 Span: 673:1 - 706:11
 File: src/postgres/include/nodes/nodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum JoinType
    {
        JOIN_INNER = 0,
        JOIN_LEFT = 1,
        JOIN_FULL = 2,
        JOIN_RIGHT = 3,
        JOIN_SEMI = 4,
        JOIN_ANTI = 5,
        JOIN_UNIQUE_OUTER = 6,
        JOIN_UNIQUE_INNER = 7
    }
}
