/* Generated by QSI

 Date: 2020-08-07
 Span: 1446:1 - 1457:11
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("JoinExpr")]
    internal sealed class JoinExpr : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_JoinExpr; }
        }

        public JoinType jointype { get; set; }

        public bool isNatural { get; set; }

        public IPg10Node larg { get; set; }

        public IPg10Node rarg { get; set; }

        public IPg10Node[] usingClause { get; set; }

        public IPg10Node quals { get; set; }

        public Alias alias { get; set; }

        public int rtindex { get; set; }
    }
}
