/* Generated by QSI

 Date: 2020-08-07
 Span: 1287:1 - 1306:11
 File: src/postgres/include/nodes/relation.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class JoinPath
    {
        public Path path { get; set; }

        public JoinType? jointype { get; set; }

        public bool? inner_unique { get; set; }

        public Path outerjoinpath { get; set; }

        public Path innerjoinpath { get; set; }

        public IPg10Node[] joinrestrictinfo { get; set; }
    }
}
