/* Generated by QSI

 Date: 2020-08-07
 Span: 1598:1 - 1605:12
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class JoinState
    {
        public PlanState ps { get; set; }

        public JoinType jointype { get; set; }

        public bool single_match { get; set; }

        public ExprState joinqual { get; set; }
    }
}
