/* Generated by QSI

 Date: 2020-08-07
 Span: 921:1 - 926:8
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Limit")]
    internal class Limit : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Limit;

        public Plan plan { get; set; }

        public IPg10Node limitOffset { get; set; }

        public IPg10Node limitCount { get; set; }
    }
}
