/* Generated by QSI

 Date: 2020-08-07
 Span: 921:1 - 926:8
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Limit
    {
        public Plan plan { get; set; }

        public IPg10Node limitOffset { get; set; }

        public IPg10Node limitCount { get; set; }
    }
}
