/* Generated by QSI

 Date: 2020-08-07
 Span: 2049:1 - 2060:13
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class LimitState
    {
        public PlanState ps { get; set; }

        public ExprState limitOffset { get; set; }

        public ExprState limitCount { get; set; }

        public int offset { get; set; }

        public int count { get; set; }

        public bool noCount { get; set; }

        public LimitStateCond lstate { get; set; }

        public int position { get; set; }

        public TupleTableSlot subSlot { get; set; }
    }
}
