/* Generated by QSI

 Date: 2020-08-07
 Span: 3013:1 - 3017:11
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("LoadStmt")]
    internal class LoadStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_LoadStmt;

        public NodeTag? type { get; set; }

        public string filename { get; set; }
    }
}
