/* Generated by QSI

 Date: 2020-08-07
 Span: 36:1 - 40:12
 File: src/postgres/include/utils/rel.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class LockRelId
    {
        public uint? relId { get; set; }

        public uint? dbId { get; set; }
    }
}
