/* Generated by QSI

 Date: 2020-08-12
 Span: 36:1 - 44:17
 File: src/postgres/include/nodes/lockoptions.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum LockWaitPolicy
    {
        LockWaitBlock = 0,
        LockWaitSkip = 1,
        LockWaitError = 2
    }
}
