/* Generated by QSI

 Date: 2020-08-07
 Span: 907:1 - 912:11
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class LockRows
    {
        public Plan plan { get; set; }

        public IPg10Node[] rowMarks { get; set; }

        public int epqParam { get; set; }
    }
}
