/* Generated by QSI

 Date: 2020-08-07
 Span: 2017:1 - 2024:16
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class LockRowsState
    {
        public PlanState ps { get; set; }

        public IPg10Node[] lr_arowMarks { get; set; }

        public EPQState lr_epqstate { get; set; }

        public HeapTupleData lr_curtuples { get; set; }

        public int lr_ntables { get; set; }
    }
}
