/* Generated by QSI

 Date: 2020-08-07
 Span: 1559:1 - 1565:15
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("LockRowsPath")]
    internal class LockRowsPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_LockRowsPath;

        public Path path { get; set; }

        public Path subpath { get; set; }

        public IPg10Node[] rowMarks { get; set; }

        public int? epqParam { get; set; }
    }
}
