/* Generated by QSI

 Date: 2020-08-07
 Span: 42:1 - 45:15
 File: src/postgres/include/utils/rel.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class LockInfoData
    {
        public LockRelId lockRelId { get; set; }
    }
}
