/* Generated by QSI

 Date: 2020-08-07
 Span: 737:1 - 743:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("LockingClause")]
    internal sealed class LockingClause : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_LockingClause; }
        }

        public IPg10Node[] lockedRels { get; set; }

        public LockClauseStrength strength { get; set; }

        public LockWaitPolicy waitPolicy { get; set; }
    }
}
