/* Generated by QSI

 Date: 2020-08-07
 Span: 1738:1 - 1744:16
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class MaterialState
    {
        public ScanState ss { get; set; }

        public int eflags { get; set; }

        public bool eof_underlying { get; set; }

        public Tuplestorestate tuplestorestate { get; set; }
    }
}
