/* Generated by QSI

 Date: 2020-08-07
 Span: 733:1 - 736:11
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Material
    {
        public Plan plan { get; set; }
    }
}
