/* Generated by QSI

 Date: 2020-08-12
 Span: 1738:1 - 1744:16
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("MaterialState")]
    internal class MaterialState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_MaterialState;

        public ScanState ss { get; set; }

        public int? eflags { get; set; }

        public bool? eof_underlying { get; set; }

        public Tuplestorestate tuplestorestate { get; set; }
    }
}
