/* Generated by QSI

 Date: 2020-08-07
 Span: 733:1 - 736:11
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Material")]
    internal class Material : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Material;

        public Plan plan { get; set; }
    }
}
