/* Generated by QSI

 Date: 2020-08-12
 Span: 1223:1 - 1227:15
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("MaterialPath")]
    internal class MaterialPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_MaterialPath;

        public Path path { get; set; }

        public Path subpath { get; set; }
    }
}
