/* Generated by QSI

 Date: 2020-08-07
 Span: 47:1 - 52:24
 File: src/postgres/include/utils/palloc.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class MemoryContextCallback
    {
        public string func { get; set; }

        public object?[] arg { get; set; }

        public MemoryContextCallback next { get; set; }
    }
}
