/* Generated by QSI

 Date: 2020-08-12
 Span: 54:1 - 70:23
 File: src/postgres/include/nodes/memnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class MemoryContextMethods
    {
        public string[] alloc { get; set; }

        public string[] free_p { get; set; }

        public string[] realloc { get; set; }

        public string[] init { get; set; }

        public string[] reset { get; set; }

        public string[] delete_context { get; set; }

        public string[] get_chunk_space { get; set; }

        public string[] is_empty { get; set; }

        public string[] stats { get; set; }
    }
}
