/* Generated by QSI

 Date: 2020-08-07
 Span: 73:1 - 86:20
 File: src/postgres/include/nodes/memnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class MemoryContextData
    {
        public NodeTag? type { get; set; }

        public bool? isReset { get; set; }

        public bool? allowInCritSection { get; set; }

        public MemoryContextMethods methods { get; set; }

        public MemoryContextData parent { get; set; }

        public MemoryContextData firstchild { get; set; }

        public MemoryContextData prevchild { get; set; }

        public MemoryContextData nextchild { get; set; }

        public string name { get; set; }

        public MemoryContextCallback reset_cbs { get; set; }
    }
}
