/* Generated by QSI

 Date: 2020-08-07
 Span: 1030:1 - 1040:19
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class MergeAppendState
    {
        public PlanState ps { get; set; }

        public PlanState[] mergeplans { get; set; }

        public int ms_nplans { get; set; }

        public int ms_nkeys { get; set; }

        public SortSupportData ms_sortkeys { get; set; }

        public TupleTableSlot[] ms_slots { get; set; }

        public binaryheap ms_heap { get; set; }

        public bool ms_initialized { get; set; }
    }
}
