/* Generated by QSI

 Date: 2020-08-07
 Span: 1195:1 - 1202:18
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("MergeAppendPath")]
    internal class MergeAppendPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_MergeAppendPath;

        public Path path { get; set; }

        public IPg10Node[] partitioned_rels { get; set; }

        public IPg10Node[] subpaths { get; set; }

        public double? limit_tuples { get; set; }
    }
}
