/* Generated by QSI

 Date: 2020-08-07
 Span: 1349:1 - 1357:12
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("MergePath")]
    internal class MergePath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_MergePath;

        public JoinPath jpath { get; set; }

        public IPg10Node[] path_mergeclauses { get; set; }

        public IPg10Node[] outersortkeys { get; set; }

        public IPg10Node[] innersortkeys { get; set; }

        public bool? skip_mark_restore { get; set; }

        public bool? materialize_inner { get; set; }
    }
}
