/* Generated by QSI

 Date: 2020-08-07
 Span: 258:1 - 270:14
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class MergeAppend
    {
        public Plan plan { get; set; }

        public IPg10Node[] partitioned_rels { get; set; }

        public IPg10Node[] mergeplans { get; set; }

        public int numCols { get; set; }

        public short sortColIdx { get; set; }

        public uint sortOperators { get; set; }

        public uint collations { get; set; }

        public bool[] nullsFirst { get; set; }
    }
}
