/* Generated by QSI

 Date: 2020-08-12
 Span: 25:1 - 25:49
 File: src/postgres/include/access/htup.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class MinimalTupleData
    {
    }
}
