/* Generated by QSI

 Date: 2020-08-07
 Span: 1054:1 - 1058:11
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum MinMaxOp
    {
        IS_GREATEST = 0,
        IS_LEAST = 1
    }
}
