/* Generated by QSI

 Date: 2020-08-07
 Span: 1060:1 - 1069:13
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class MinMaxExpr
    {
        public Expr xpr { get; set; }

        public uint minmaxtype { get; set; }

        public uint minmaxcollid { get; set; }

        public uint inputcollid { get; set; }

        public MinMaxOp op { get; set; }

        public IPg10Node[] args { get; set; }

        public int location { get; set; }
    }
}
