/* Generated by QSI

 Date: 2020-08-12
 Span: 1060:1 - 1069:13
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("MinMaxExpr")]
    internal class MinMaxExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_MinMaxExpr;

        public IPg10Node xpr { get; set; }

        public uint? minmaxtype { get; set; }

        public uint? minmaxcollid { get; set; }

        public uint? inputcollid { get; set; }

        public MinMaxOp? op { get; set; }

        public IPg10Node[] args { get; set; }
    }
}
