/* Generated by QSI

 Date: 2020-08-12
 Span: 2090:1 - 2101:16
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("MinMaxAggInfo")]
    internal class MinMaxAggInfo : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_MinMaxAggInfo;

        public uint? aggfnoid { get; set; }

        public uint? aggsortop { get; set; }

        public IPg10ExpressionNode target { get; set; }

        public PlannerInfo subroot { get; set; }

        public Path path { get; set; }

        public double? pathcost { get; set; }

        public Param param { get; set; }
    }
}
