/* Generated by QSI

 Date: 2020-08-07
 Span: 957:1 - 1002:19
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ModifyTableState")]
    internal class ModifyTableState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ModifyTableState;

        public PlanState ps { get; set; }

        public CmdType? operation { get; set; }

        public bool? canSetTag { get; set; }

        public bool? mt_done { get; set; }

        public PlanState[] mt_plans { get; set; }

        public int? mt_nplans { get; set; }

        public int? mt_whichplan { get; set; }

        public ResultRelInfo resultRelInfo { get; set; }

        public ResultRelInfo rootResultRelInfo { get; set; }

        public IPg10Node[][] mt_arowmarks { get; set; }

        public EPQState mt_epqstate { get; set; }

        public bool? fireBSTriggers { get; set; }

        public OnConflictAction? mt_onconflict { get; set; }

        public IPg10Node[] mt_arbiterindexes { get; set; }

        public TupleTableSlot mt_existing { get; set; }

        public IPg10Node[] mt_excludedtlist { get; set; }

        public TupleTableSlot mt_conflproj { get; set; }

        public PartitionDispatchData[] mt_partition_dispatch_info { get; set; }

        public int? mt_num_dispatch { get; set; }

        public int? mt_num_partitions { get; set; }

        public ResultRelInfo mt_partitions { get; set; }

        public TupleConversionMap[] mt_partition_tupconv_maps { get; set; }

        public TupleTableSlot mt_partition_tuple_slot { get; set; }

        public TransitionCaptureState mt_transition_capture { get; set; }

        public TransitionCaptureState mt_oc_transition_capture { get; set; }

        public TupleConversionMap[] mt_transition_tupconv_maps { get; set; }
    }
}
