/* Generated by QSI

 Date: 2020-08-12
 Span: 1574:1 - 1590:18
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ModifyTablePath")]
    internal class ModifyTablePath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ModifyTablePath;

        public Path path { get; set; }

        public CmdType? operation { get; set; }

        public bool? canSetTag { get; set; }

        public uint? nominalRelation { get; set; }

        public IPg10Node[] partitioned_rels { get; set; }

        public IPg10Node[] resultRelations { get; set; }

        public IPg10Node[] subpaths { get; set; }

        public IPg10Node[] subroots { get; set; }

        public IPg10Node[] withCheckOptionLists { get; set; }

        public IPg10Node[] returningLists { get; set; }

        public IPg10Node[] rowMarks { get; set; }

        public OnConflictExpr onconflict { get; set; }

        public int? epqParam { get; set; }
    }
}
