/* Generated by QSI

 Date: 2020-08-07
 Span: 454:1 - 460:17
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("MultiAssignRef")]
    internal class MultiAssignRef : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_MultiAssignRef;

        public NodeTag? type { get; set; }

        public IPg10Node source { get; set; }

        public int? colno { get; set; }

        public int? ncolumns { get; set; }
    }
}
