/* Generated by QSI

 Date: 2020-08-12
 Span: 1524:1 - 1530:27
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("NamedTuplestoreScanState")]
    internal class NamedTuplestoreScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_NamedTuplestoreScanState;

        public ScanState ss { get; set; }

        public int? readptr { get; set; }

        public tupleDesc[] tupdesc { get; set; }

        public Tuplestorestate[] relation { get; set; }
    }
}
