/* Generated by QSI

 Date: 2020-08-12
 Span: 571:9 - 574:2
 File: src/postgres/include/c.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class nameData
    {
        public string data { get; set; }
    }
}
