/* Generated by QSI

 Date: 2020-08-07
 Span: 1524:1 - 1530:27
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class NamedTuplestoreScanState
    {
        public ScanState ss { get; set; }

        public int readptr { get; set; }

        public tupleDesc tupdesc { get; set; }

        public Tuplestorestate relation { get; set; }
    }
}
