/* Generated by QSI

 Date: 2020-08-07
 Span: 547:1 - 551:22
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("NamedTuplestoreScan")]
    internal class NamedTuplestoreScan : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_NamedTuplestoreScan;

        public Scan scan { get; set; }

        public string enrname { get; set; }
    }
}
