/* Generated by QSI

 Date: 2020-08-07
 Span: 547:1 - 551:22
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class NamedTuplestoreScan
    {
        public Scan scan { get; set; }

        public string enrname { get; set; }
    }
}
