/* Generated by QSI

 Date: 2020-08-07
 Span: 475:1 - 482:15
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class NamedArgExpr
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public string name { get; set; }

        public int argnumber { get; set; }

        public int location { get; set; }
    }
}
