/* Generated by QSI

 Date: 2020-08-12
 Span: 689:1 - 694:16
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("NestLoopParam")]
    internal class NestLoopParam : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_NestLoopParam;

        public int? paramno { get; set; }

        public Var paramval { get; set; }
    }
}
