/* Generated by QSI

 Date: 2020-08-12
 Span: 683:1 - 687:11
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("NestLoop")]
    internal class NestLoop : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_NestLoop;

        public Join join { get; set; }

        public IPg10Node[] nestParams { get; set; }
    }
}
