/* Generated by QSI

 Date: 2020-08-07
 Span: 689:1 - 694:16
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("NestLoopParam")]
    internal sealed class NestLoopParam : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_NestLoopParam; }
        }

        public int paramno { get; set; }

        public Var paramval { get; set; }
    }
}
