/* Generated by QSI

 Date: 2020-08-07
 Span: 1615:1 - 1621:16
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class NestLoopState
    {
        public JoinState js { get; set; }

        public bool nl_NeedNewOuter { get; set; }

        public bool nl_MatchedOuter { get; set; }

        public TupleTableSlot nl_NullInnerTupleSlot { get; set; }
    }
}
