/* Generated by QSI

 Date: 2020-08-07
 Span: 683:1 - 687:11
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class NestLoop
    {
        public Join join { get; set; }

        public IPg10Node[] nestParams { get; set; }
    }
}
