/* Generated by QSI

 Date: 2020-08-07
 Span: 1312:1 - 1312:26
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("NestPath")]
    internal class NestPath : JoinPath
    {
        public NodeTag Type => NodeTag.T_NestPath;
    }
}
