/* Generated by QSI

 Date: 2020-08-07
 Span: 1289:1 - 1294:16
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class NextValueExpr
    {
        public Expr xpr { get; set; }

        public uint seqid { get; set; }

        public uint typeId { get; set; }
    }
}
