/* Generated by QSI

 Date: 2020-08-07
 Span: 2886:1 - 2891:13
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("NotifyStmt")]
    internal sealed class NotifyStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_NotifyStmt; }
        }

        public string conditionname { get; set; }

        public string payload { get; set; }
    }
}
