/* Generated by QSI

 Date: 2020-08-12
 Span: 1177:1 - 1184:11
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("NullTest")]
    internal class NullTest : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_NullTest;

        public IPg10ExpressionNode xpr { get; set; }

        public IPg10ExpressionNode arg { get; set; }

        public NullTestType? nulltesttype { get; set; }

        public bool? argisrow { get; set; }
    }
}
