/* Generated by QSI

 Date: 2020-08-12
 Span: 1172:1 - 1175:15
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum NullTestType
    {
        IS_NULL = 0,
        IS_NOT_NULL = 1
    }
}
