/* Generated by QSI

 Date: 2020-08-12
 Span: 524:1 - 524:26
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("NullIfExpr")]
    internal class NullIfExpr : OpExpr
    {
        public override NodeTag Type => NodeTag.T_NullIfExpr;
    }
}
