/* Generated by QSI

 Date: 2020-08-07
 Span: 1177:1 - 1184:11
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class NullTest
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public NullTestType nulltesttype { get; set; }

        public bool argisrow { get; set; }

        public int location { get; set; }
    }
}
