/* Generated by QSI

 Date: 2020-08-07
 Span: 1351:1 - 1359:19
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("OnConflictClause")]
    internal sealed class OnConflictClause : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_OnConflictClause; }
        }

        public OnConflictAction action { get; set; }

        public InferClause infer { get; set; }

        public IPg10Node[] targetList { get; set; }

        public IPg10Node whereClause { get; set; }

        public int location { get; set; }
    }
}
