/* Generated by QSI

 Date: 2020-08-12
 Span: 47:1 - 53:17
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum OnCommitAction
    {
        ONCOMMIT_NOOP = 0,
        ONCOMMIT_PRESERVE_ROWS = 1,
        ONCOMMIT_DELETE_ROWS = 2,
        ONCOMMIT_DROP = 3
    }
}
