/* Generated by QSI

 Date: 2020-08-07
 Span: 799:1 - 804:19
 File: src/postgres/include/nodes/nodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum OnConflictAction
    {
        ONCONFLICT_NONE = 0,
        ONCONFLICT_NOTHING = 1,
        ONCONFLICT_UPDATE = 2
    }
}
