/* Generated by QSI

 Date: 2020-08-07
 Span: 493:1 - 504:9
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class OpExpr
    {
        public Expr xpr { get; set; }

        public uint opno { get; set; }

        public uint opfuncid { get; set; }

        public uint opresulttype { get; set; }

        public bool opretset { get; set; }

        public uint opcollid { get; set; }

        public uint inputcollid { get; set; }

        public IPg10Node[] args { get; set; }

        public int location { get; set; }
    }
}
