/* Generated by QSI

 Date: 2020-08-12
 Span: 493:1 - 504:9
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("OpExpr")]
    internal class OpExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_OpExpr;

        public IPg10Node xpr { get; set; }

        public uint? opno { get; set; }

        public uint? opfuncid { get; set; }

        public uint? opresulttype { get; set; }

        public bool? opretset { get; set; }

        public uint? opcollid { get; set; }

        public uint? inputcollid { get; set; }

        public IPg10Node[] args { get; set; }
    }
}
