/* Generated by QSI

 Date: 2020-08-07
 Span: 30:1 - 35:17
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum OverridingKind
    {
        OVERRIDING_NOT_SET = 0,
        OVERRIDING_USER_VALUE = 1,
        OVERRIDING_SYSTEM_VALUE = 2
    }
}
