/* Generated by QSI

 Date: 2020-08-12
 Span: 71:1 - 76:14
 File: src/postgres/include/lib/pairingheap.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class pairingheap
    {
        public string[] ph_compare { get; set; }

        public object[] ph_arg { get; set; }

        public pairingheap_node[] ph_root { get; set; }
    }
}
