/* Generated by QSI

 Date: 2020-08-07
 Span: 30:1 - 35:19
 File: src/postgres/include/lib/pairingheap.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class pairingheap_node
    {
        public pairingheap_node first_child { get; set; }

        public pairingheap_node next_sibling { get; set; }

        public pairingheap_node prev_or_parent { get; set; }
    }
}
