/* Generated by QSI

 Date: 2020-08-07
 Span: 97:1 - 102:16
 File: src/postgres/include/nodes/params.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class ParamExecData
    {
        public object?[] execPlan { get; set; }

        public uint? value { get; set; }

        public bool? isnull { get; set; }
    }
}
