/* Generated by QSI

 Date: 2020-08-07
 Span: 1930:2 - 1930:29
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class ParallelExecutorInfo
    {
    }
}
