/* Generated by QSI

 Date: 2020-08-07
 Span: 1323:1 - 1333:26
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ParallelBitmapHeapState
    {
        public uint tbmiterator { get; set; }

        public uint prefetch_iterator { get; set; }

        public byte mutex { get; set; }

        public int prefetch_pages { get; set; }

        public int prefetch_target { get; set; }

        public SharedBitmapState state { get; set; }

        public ConditionVariable cv { get; set; }

        public string phs_snapshot_data { get; set; }
    }
}
