/* Generated by QSI

 Date: 2020-08-12
 Span: 241:1 - 250:8
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Param")]
    internal class Param : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Param;

        public IPg10Node xpr { get; set; }

        public ParamKind? paramkind { get; set; }

        public int? paramid { get; set; }

        public uint? paramtype { get; set; }

        public int? paramtypmod { get; set; }

        public uint? paramcollid { get; set; }
    }
}
