/* Generated by QSI

 Date: 2020-08-12
 Span: 909:1 - 916:16
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ParamPathInfo")]
    internal class ParamPathInfo : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ParamPathInfo;

        public Bitmapset[] ppi_req_outer { get; set; }

        public double? ppi_rows { get; set; }

        public IPg10Node[] ppi_clauses { get; set; }
    }
}
