/* Generated by QSI

 Date: 2020-08-12
 Span: 54:1 - 60:18
 File: src/postgres/include/nodes/params.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class ParamExternData
    {
        public uint? value { get; set; }

        public bool? isnull { get; set; }

        public ushort? pflags { get; set; }

        public uint? ptype { get; set; }
    }
}
