/* Generated by QSI

 Date: 2020-08-07
 Span: 241:1 - 250:8
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Param
    {
        public Expr xpr { get; set; }

        public ParamKind paramkind { get; set; }

        public int paramid { get; set; }

        public uint paramtype { get; set; }

        public int paramtypmod { get; set; }

        public uint paramcollid { get; set; }

        public int location { get; set; }
    }
}
