/* Generated by QSI

 Date: 2020-08-07
 Span: 233:1 - 239:12
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum ParamKind
    {
        PARAM_EXTERN = 0,
        PARAM_EXEC = 1,
        PARAM_SUBLINK = 2,
        PARAM_MULTIEXPR = 3
    }
}
