/* Generated by QSI

 Date: 2020-08-07
 Span: 28:9 - 28:38
 File: src/postgres/include/catalog/partition.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class PartitionBoundInfoData
    {
    }
}
