/* Generated by QSI

 Date: 2020-08-07
 Span: 978:2 - 978:30
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class PartitionDispatchData
    {
    }
}
