/* Generated by QSI

 Date: 2020-08-07
 Span: 780:1 - 786:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PartitionSpec")]
    internal sealed class PartitionSpec : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_PartitionSpec; }
        }

        public string strategy { get; set; }

        public IPg10Node[] partParams { get; set; }

        public int location { get; set; }
    }
}
