/* Generated by QSI

 Date: 2020-08-07
 Span: 819:1 - 824:26
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum PartitionRangeDatumKind
    {
        PARTITION_RANGE_DATUM_MINVALUE = -1,
        PARTITION_RANGE_DATUM_VALUE = 0,
        PARTITION_RANGE_DATUM_MAXVALUE = 1
    }
}
