/* Generated by QSI

 Date: 2020-08-12
 Span: 840:1 - 845:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PartitionCmd")]
    internal class PartitionCmd : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PartitionCmd;

        public RangeVar name { get; set; }

        public PartitionBoundSpec bound { get; set; }
    }
}
