/* Generated by QSI

 Date: 2020-08-12
 Span: 60:1 - 69:24
 File: src/postgres/include/catalog/partition.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class PartitionDispatchData
    {
        public RelationData reldesc { get; set; }

        public PartitionKeyData key { get; set; }

        public IPg10Node[] keystate { get; set; }

        public PartitionDescData partdesc { get; set; }

        public TupleTableSlot tupslot { get; set; }

        public TupleConversionMap tupmap { get; set; }

        public int?[] indexes { get; set; }
    }
}
