/* Generated by QSI

 Date: 2020-08-07
 Span: 826:1 - 835:22
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PartitionRangeDatum")]
    internal class PartitionRangeDatum : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PartitionRangeDatum;

        public NodeTag? type { get; set; }

        public PartitionRangeDatumKind? kind { get; set; }

        public IPg10Node value { get; set; }
    }
}
