/* Generated by QSI

 Date: 2020-08-12
 Span: 218:2 - 218:27
 File: src/postgres/include/utils/rel.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class PgStat_TableStatus
    {
    }
}
