/* Generated by QSI

 Date: 2020-08-12
 Span: 1862:1 - 1869:17
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PlaceHolderVar")]
    internal class PlaceHolderVar : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PlaceHolderVar;

        public IPg10ExpressionNode xpr { get; set; }

        public IPg10ExpressionNode phexpr { get; set; }

        public Bitmapset phrels { get; set; }

        public uint? phid { get; set; }

        public uint? phlevelsup { get; set; }
    }
}
