/* Generated by QSI

 Date: 2020-08-12
 Span: 2073:1 - 2083:18
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PlaceHolderInfo")]
    internal class PlaceHolderInfo : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PlaceHolderInfo;

        public uint? phid { get; set; }

        public PlaceHolderVar[] ph_var { get; set; }

        public Bitmapset[] ph_eval_at { get; set; }

        public Bitmapset[] ph_lateral { get; set; }

        public Bitmapset[] ph_needed { get; set; }

        public int? ph_width { get; set; }
    }
}
