/* Generated by QSI

 Date: 2020-08-07
 Span: 2150:1 - 2156:19
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PlannerParamItem")]
    internal class PlannerParamItem : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PlannerParamItem;

        public NodeTag? type { get; set; }

        public IPg10Node item { get; set; }

        public int? paramId { get; set; }
    }
}
