/* Generated by QSI

 Date: 2020-08-07
 Span: 1010:1 - 1021:14
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PlanRowMark")]
    internal class PlanRowMark : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PlanRowMark;

        public NodeTag? type { get; set; }

        public uint? rti { get; set; }

        public uint? prti { get; set; }

        public uint? rowmarkId { get; set; }

        public RowMarkType? markType { get; set; }

        public int? allMarkTypes { get; set; }

        public LockClauseStrength? strength { get; set; }

        public LockWaitPolicy? waitPolicy { get; set; }

        public bool? isParent { get; set; }
    }
}
