/* Generated by QSI

 Date: 2020-08-12
 Span: 41:1 - 99:14
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PlannedStmt")]
    internal class PlannedStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PlannedStmt;

        public CmdType? commandType { get; set; }

        public uint? queryId { get; set; }

        public bool? hasReturning { get; set; }

        public bool? hasModifyingCTE { get; set; }

        public bool? canSetTag { get; set; }

        public bool? transientPlan { get; set; }

        public bool? dependsOnRole { get; set; }

        public bool? parallelModeNeeded { get; set; }

        public Plan planTree { get; set; }

        public IPg10Node[] rtable { get; set; }

        public IPg10Node[] resultRelations { get; set; }

        public IPg10Node[] nonleafResultRelations { get; set; }

        public IPg10Node[] rootResultRelations { get; set; }

        public IPg10Node[] subplans { get; set; }

        public Bitmapset rewindPlanIDs { get; set; }

        public IPg10Node[] rowMarks { get; set; }

        public IPg10Node[] relationOids { get; set; }

        public IPg10Node[] invalItems { get; set; }

        public int? nParamExec { get; set; }

        public IPg10Node utilityStmt { get; set; }

        public int? stmt_location { get; set; }

        public int? stmt_len { get; set; }
    }
}
