/* Generated by QSI

 Date: 2020-08-07
 Span: 845:1 - 885:12
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PlanState")]
    internal sealed class PlanState : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_PlanState; }
        }

        public Plan plan { get; set; }

        public EState state { get; set; }

        public string ExecProcNode { get; set; }

        public string ExecProcNodeReal { get; set; }

        public Instrumentation instrument { get; set; }

        public WorkerInstrumentation worker_instrument { get; set; }

        public ExprState qual { get; set; }

        public PlanState lefttree { get; set; }

        public PlanState righttree { get; set; }

        public IPg10Node[] initPlan { get; set; }

        public IPg10Node[] subPlan { get; set; }

        public Bitmapset chgParam { get; set; }

        public TupleTableSlot ps_ResultTupleSlot { get; set; }

        public ExprContext ps_ExprContext { get; set; }

        public ProjectionInfo ps_ProjInfo { get; set; }
    }
}
