/* Generated by QSI

 Date: 2020-08-12
 Span: 151:1 - 317:14
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PlannerInfo")]
    internal class PlannerInfo : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PlannerInfo;

        public Query parse { get; set; }

        public PlannerGlobal glob { get; set; }

        public uint? query_level { get; set; }

        public PlannerInfo parent_root { get; set; }

        public IPg10Node[] plan_params { get; set; }

        public Bitmapset outer_params { get; set; }

        public RelOptInfo[] simple_rel_array { get; set; }

        public int? simple_rel_array_size { get; set; }

        public RangeTblEntry[] simple_rte_array { get; set; }

        public Bitmapset all_baserels { get; set; }

        public Bitmapset nullable_baserels { get; set; }

        public IPg10Node[] join_rel_list { get; set; }

        public HTAB join_rel_hash { get; set; }

        public IPg10Node[][] join_rel_level { get; set; }

        public int? join_cur_level { get; set; }

        public IPg10Node[] init_plans { get; set; }

        public IPg10Node[] cte_plan_ids { get; set; }

        public IPg10Node[] multiexpr_params { get; set; }

        public IPg10Node[] eq_classes { get; set; }

        public IPg10Node[] canon_pathkeys { get; set; }

        public IPg10Node[] left_join_clauses { get; set; }

        public IPg10Node[] right_join_clauses { get; set; }

        public IPg10Node[] full_join_clauses { get; set; }

        public IPg10Node[] join_info_list { get; set; }

        public IPg10Node[] append_rel_list { get; set; }

        public IPg10Node[] pcinfo_list { get; set; }

        public IPg10Node[] rowMarks { get; set; }

        public IPg10Node[] placeholder_list { get; set; }

        public IPg10Node[] fkey_list { get; set; }

        public IPg10Node[] query_pathkeys { get; set; }

        public IPg10Node[] group_pathkeys { get; set; }

        public IPg10Node[] window_pathkeys { get; set; }

        public IPg10Node[] distinct_pathkeys { get; set; }

        public IPg10Node[] sort_pathkeys { get; set; }

        public IPg10Node[] initial_rels { get; set; }

        public IPg10Node[][] upper_rels { get; set; }

        public PathTarget[] upper_targets { get; set; }

        public IPg10Node[] processed_tlist { get; set; }

        public short? grouping_map { get; set; }

        public IPg10Node[] minmax_aggs { get; set; }

        public MemoryContext planner_cxt { get; set; }

        public double? total_table_pages { get; set; }

        public double? tuple_fraction { get; set; }

        public double? limit_tuples { get; set; }

        public uint? qual_security_level { get; set; }

        public bool? hasInheritedTarget { get; set; }

        public bool? hasJoinRTEs { get; set; }

        public bool? hasLateralRTEs { get; set; }

        public bool? hasDeletedRTEs { get; set; }

        public bool? hasHavingQual { get; set; }

        public bool? hasPseudoConstantQuals { get; set; }

        public bool? hasRecursion { get; set; }

        public int? wt_param_id { get; set; }

        public Path non_recursive_path { get; set; }

        public Bitmapset curOuterRels { get; set; }

        public IPg10Node[] curOuterParams { get; set; }

        public object?[] join_search_private { get; set; }
    }
}
