/* Generated by QSI

 Date: 2020-08-07
 Span: 1033:1 - 1038:16
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PlanInvalItem")]
    internal class PlanInvalItem : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PlanInvalItem;

        public NodeTag? type { get; set; }

        public int? cacheId { get; set; }

        public uint? hashValue { get; set; }
    }
}
