/* Generated by QSI

 Date: 2020-08-07
 Span: 3283:1 - 3289:14
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("PrepareStmt")]
    internal class PrepareStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_PrepareStmt;

        public NodeTag? type { get; set; }

        public string name { get; set; }

        public IPg10Node[] argtypes { get; set; }

        public IPg10Node query { get; set; }
    }
}
