/* Generated by QSI

 Date: 2020-08-12
 Span: 30:1 - 34:16
 File: src/postgres/include/storage/proclist_types.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class proclist_head
    {
        public int? head { get; set; }

        public int? tail { get; set; }
    }
}
