/* Generated by QSI

 Date: 2020-08-07
 Span: 944:1 - 951:18
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ProjectSetState")]
    internal class ProjectSetState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ProjectSetState;

        public PlanState ps { get; set; }

        public IPg10Node[] elems { get; set; }

        public ExprDoneCond? elemdone { get; set; }

        public int? nelems { get; set; }

        public bool? pending_srf_tuples { get; set; }
    }
}
