/* Generated by QSI

 Date: 2020-08-12
 Span: 200:1 - 203:13
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ProjectSet")]
    internal class ProjectSet : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ProjectSet;

        public Plan plan { get; set; }
    }
}
