/* Generated by QSI

 Date: 2020-08-07
 Span: 200:1 - 203:13
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ProjectSet
    {
        public Plan plan { get; set; }
    }
}
