/* Generated by QSI

 Date: 2020-08-07
 Span: 292:1 - 299:17
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ProjectionInfo")]
    internal sealed class ProjectionInfo : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_ProjectionInfo; }
        }

        public ExprState pi_state { get; set; }

        public ExprContext pi_exprContext { get; set; }
    }
}
