/* Generated by QSI

 Date: 2020-08-07
 Span: 944:1 - 951:18
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ProjectSetState
    {
        public PlanState ps { get; set; }

        public IPg10Node[] elems { get; set; }

        public ExprDoneCond elemdone { get; set; }

        public int nelems { get; set; }

        public bool pending_srf_tuples { get; set; }
    }
}
