/* Generated by QSI

 Date: 2020-08-07
 Span: 1389:1 - 1394:17
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ProjectionPath")]
    internal class ProjectionPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ProjectionPath;

        public Path path { get; set; }

        public Path subpath { get; set; }

        public bool? dummypp { get; set; }
    }
}
