/* Generated by QSI

 Date: 2020-08-07
 Span: 1401:1 - 1405:17
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ProjectSetPath")]
    internal class ProjectSetPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ProjectSetPath;

        public Path path { get; set; }

        public Path subpath { get; set; }
    }
}
