/* Generated by QSI

 Date: 2020-08-07
 Span: 74:1 - 79:21
 File: src/postgres/include/catalog/pg_publication.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class PublicationActions
    {
        public bool? pubinsert { get; set; }

        public bool? pubupdate { get; set; }

        public bool? pubdelete { get; set; }
    }
}
