/* Generated by QSI

 Date: 2020-08-07
 Span: 43:1 - 47:11
 File: src/postgres/include/nodes/relation.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class QualCost
    {
        public double? startup { get; set; }

        public double? per_tuple { get; set; }
    }
}
