/* Generated by QSI

 Date: 2020-08-12
 Span: 64:1 - 64:49
 File: src/postgres/include/utils/queryenvironment.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class QueryEnvironment
    {
    }
}
