/* Generated by QSI

 Date: 2020-08-07
 Span: 38:1 - 45:14
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum QuerySource
    {
        QSRC_ORIGINAL = 0,
        QSRC_PARSER = 1,
        QSRC_INSTEAD_RULE = 2,
        QSRC_QUAL_INSTEAD_RULE = 3,
        QSRC_NON_INSTEAD_RULE = 4
    }
}
