/* Generated by QSI

 Date: 2020-08-07
 Span: 608:1 - 616:19
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RangeTableSample")]
    internal sealed class RangeTableSample : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_RangeTableSample; }
        }

        public IPg10Node relation { get; set; }

        public IPg10Node[] method { get; set; }

        public IPg10Node[] args { get; set; }

        public IPg10Node repeatable { get; set; }

        public int location { get; set; }
    }
}
