/* Generated by QSI

 Date: 2020-08-12
 Span: 943:1 - 1061:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RangeTblEntry")]
    internal class RangeTblEntry : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_RangeTblEntry;

        public RTEKind? rtekind { get; set; }

        public uint? relid { get; set; }

        public char? relkind { get; set; }

        public TableSampleClause tablesample { get; set; }

        public Query subquery { get; set; }

        public bool? security_barrier { get; set; }

        public JoinType? jointype { get; set; }

        public IPg10Node[] joinaliasvars { get; set; }

        public IPg10Node[] functions { get; set; }

        public bool? funcordinality { get; set; }

        public TableFunc tablefunc { get; set; }

        public IPg10Node[] values_lists { get; set; }

        public string ctename { get; set; }

        public uint? ctelevelsup { get; set; }

        public bool? self_reference { get; set; }

        public IPg10Node[] coltypes { get; set; }

        public IPg10Node[] coltypmods { get; set; }

        public IPg10Node[] colcollations { get; set; }

        public string enrname { get; set; }

        public double? enrtuples { get; set; }

        public Alias alias { get; set; }

        public Alias eref { get; set; }

        public bool? lateral { get; set; }

        public bool? inh { get; set; }

        public bool? inFromCl { get; set; }

        public uint? requiredPerms { get; set; }

        public uint? checkAsUser { get; set; }

        public Bitmapset selectedCols { get; set; }

        public Bitmapset insertedCols { get; set; }

        public Bitmapset updatedCols { get; set; }

        public IPg10Node[] securityQuals { get; set; }
    }
}
