/* Generated by QSI

 Date: 2020-08-12
 Span: 553:1 - 563:16
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RangeFunction")]
    internal class RangeFunction : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_RangeFunction;

        public bool? lateral { get; set; }

        public bool? ordinality { get; set; }

        public bool? is_rowsfrom { get; set; }

        public IPg10Node[] functions { get; set; }

        public Alias alias { get; set; }

        public IPg10Node[] coldeflist { get; set; }
    }
}
