/* Generated by QSI

 Date: 2020-08-12
 Span: 63:1 - 74:11
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RangeVar")]
    internal class RangeVar : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_RangeVar;

        public string catalogname { get; set; }

        public string schemaname { get; set; }

        public string relname { get; set; }

        public bool? inh { get; set; }

        public char? relpersistence { get; set; }

        public Alias[] alias { get; set; }
    }
}
