/* Generated by QSI

 Date: 2020-08-12
 Span: 608:1 - 616:19
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RangeTableSample")]
    internal class RangeTableSample : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_RangeTableSample;

        public IPg10Node[] relation { get; set; }

        public IPg10Node[] method { get; set; }

        public IPg10Node[] args { get; set; }

        public IPg10Node[] repeatable { get; set; }
    }
}
