/* Generated by QSI

 Date: 2020-08-07
 Span: 568:1 - 578:17
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RangeTableFunc")]
    internal sealed class RangeTableFunc : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_RangeTableFunc; }
        }

        public bool lateral { get; set; }

        public IPg10Node docexpr { get; set; }

        public IPg10Node rowexpr { get; set; }

        public IPg10Node[] namespaces { get; set; }

        public IPg10Node[] columns { get; set; }

        public Alias alias { get; set; }

        public int location { get; set; }
    }
}
