/* Generated by QSI

 Date: 2020-08-07
 Span: 1417:1 - 1421:14
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RangeTblRef")]
    internal class RangeTblRef : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_RangeTblRef;

        public NodeTag? type { get; set; }

        public int? rtindex { get; set; }
    }
}
