/* Generated by QSI

 Date: 2020-08-07
 Span: 23:1 - 23:15
 File: src/postgres/include/utils/plancache.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RawStmt")]
    internal sealed class RawStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_RawStmt; }
        }

        public IPg10Node stmt { get; set; }

        public int stmt_location { get; set; }

        public int stmt_len { get; set; }
    }
}
