/* Generated by QSI

 Date: 2020-08-12
 Span: 23:1 - 23:15
 File: src/postgres/include/utils/plancache.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RawStmt")]
    internal class RawStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_RawStmt;

        public IPg10Node[] stmt { get; set; }

        public int? stmt_location { get; set; }

        public int? stmt_len { get; set; }
    }
}
