/* Generated by QSI

 Date: 2020-08-07
 Span: 280:1 - 290:17
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class RecursiveUnion
    {
        public Plan plan { get; set; }

        public int wtParam { get; set; }

        public int numCols { get; set; }

        public short dupColIdx { get; set; }

        public uint dupOperators { get; set; }

        public int numGroups { get; set; }
    }
}
