/* Generated by QSI

 Date: 2020-08-07
 Span: 1053:1 - 1066:22
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class RecursiveUnionState
    {
        public PlanState ps { get; set; }

        public bool recursing { get; set; }

        public bool intermediate_empty { get; set; }

        public Tuplestorestate working_table { get; set; }

        public Tuplestorestate intermediate_table { get; set; }

        public FmgrInfo eqfunctions { get; set; }

        public FmgrInfo hashfunctions { get; set; }

        public MemoryContextData[] tempContext { get; set; }

        public TupleHashTableData hashtable { get; set; }

        public MemoryContextData[] tableContext { get; set; }
    }
}
