/* Generated by QSI

 Date: 2020-08-12
 Span: 1053:1 - 1066:22
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RecursiveUnionState")]
    internal class RecursiveUnionState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_RecursiveUnionState;

        public PlanState ps { get; set; }

        public bool? recursing { get; set; }

        public bool? intermediate_empty { get; set; }

        public Tuplestorestate[] working_table { get; set; }

        public Tuplestorestate[] intermediate_table { get; set; }

        public FmgrInfo[] eqfunctions { get; set; }

        public FmgrInfo[] hashfunctions { get; set; }

        public MemoryContext tempContext { get; set; }

        public TupleHashTableData[] hashtable { get; set; }

        public MemoryContext tableContext { get; set; }
    }
}
