/* Generated by QSI

 Date: 2020-08-07
 Span: 3151:1 - 3157:21
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RefreshMatViewStmt")]
    internal sealed class RefreshMatViewStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_RefreshMatViewStmt; }
        }

        public bool concurrent { get; set; }

        public bool skipData { get; set; }

        public RangeVar relation { get; set; }
    }
}
