/* Generated by QSI

 Date: 2020-08-07
 Span: 3227:1 - 3235:14
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ReindexStmt")]
    internal sealed class ReindexStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_ReindexStmt; }
        }

        public ReindexObjectType kind { get; set; }

        public RangeVar relation { get; set; }

        public char name { get; set; }

        public int options { get; set; }
    }
}
