/* Generated by QSI

 Date: 2020-08-07
 Span: 3218:1 - 3225:20
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum ReindexObjectType
    {
        REINDEX_OBJECT_INDEX = 0,
        REINDEX_OBJECT_TABLE = 1,
        REINDEX_OBJECT_SCHEMA = 2,
        REINDEX_OBJECT_SYSTEM = 3,
        REINDEX_OBJECT_DATABASE = 4
    }
}
