/* Generated by QSI

 Date: 2020-08-12
 Span: 3227:1 - 3235:14
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ReindexStmt")]
    internal class ReindexStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ReindexStmt;

        public ReindexObjectType? kind { get; set; }

        public RangeVar[] relation { get; set; }

        public char[] name { get; set; }

        public int? options { get; set; }
    }
}
