/* Generated by QSI

 Date: 2020-08-07
 Span: 788:1 - 797:14
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class RelabelType
    {
        public Expr xpr { get; set; }

        public Expr arg { get; set; }

        public uint resulttype { get; set; }

        public int resulttypmod { get; set; }

        public uint resultcollid { get; set; }

        public CoercionForm relabelformat { get; set; }

        public int location { get; set; }
    }
}
