/* Generated by QSI

 Date: 2020-08-07
 Span: 21:9 - 21:28
 File: src/postgres/include/utils/relcache.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class RelationData
    {
    }
}
