/* Generated by QSI

 Date: 2020-08-12
 Span: 57:1 - 62:14
 File: src/postgres/include/storage/relfilenode.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class RelFileNode
    {
        public uint? spcNode { get; set; }

        public uint? dbNode { get; set; }

        public uint? relNode { get; set; }
    }
}
