/* Generated by QSI

 Date: 2020-08-07
 Span: 492:1 - 499:13
 File: src/postgres/include/nodes/relation.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum RelOptKind
    {
        RELOPT_BASEREL = 0,
        RELOPT_JOINREL = 1,
        RELOPT_OTHER_MEMBER_REL = 2,
        RELOPT_UPPER_REL = 3,
        RELOPT_DEADREL = 4
    }
}
