/* Generated by QSI

 Date: 2020-08-07
 Span: 2799:1 - 2811:13
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RenameStmt")]
    internal sealed class RenameStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_RenameStmt; }
        }

        public ObjectType renameType { get; set; }

        public ObjectType relationType { get; set; }

        public RangeVar relation { get; set; }

        public IPg10Node @object { get; set; }

        public string subname { get; set; }

        public string newname { get; set; }

        public DropBehavior behavior { get; set; }

        public bool missing_ok { get; set; }
    }
}
