/* Generated by QSI

 Date: 2020-08-07
 Span: 436:1 - 443:12
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ResTarget")]
    internal sealed class ResTarget : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_ResTarget; }
        }

        public string name { get; set; }

        public IPg10Node[] indirection { get; set; }

        public IPg10Node val { get; set; }

        public int location { get; set; }
    }
}
