/* Generated by QSI

 Date: 2020-08-07
 Span: 1211:1 - 1215:13
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ResultPath")]
    internal class ResultPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ResultPath;

        public Path path { get; set; }

        public IPg10Node[] quals { get; set; }
    }
}
