/* Generated by QSI

 Date: 2020-08-07
 Span: 929:1 - 935:14
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ResultState
    {
        public PlanState ps { get; set; }

        public ExprState resconstantqual { get; set; }

        public bool rs_done { get; set; }

        public bool rs_checkqual { get; set; }
    }
}
