/* Generated by QSI

 Date: 2020-08-07
 Span: 929:1 - 935:14
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ResultState")]
    internal class ResultState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ResultState;

        public PlanState ps { get; set; }

        public ExprState resconstantqual { get; set; }

        public bool? rs_done { get; set; }

        public bool? rs_checkqual { get; set; }
    }
}
