/* Generated by QSI

 Date: 2020-08-12
 Span: 262:1 - 275:16
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ReturnSetInfo")]
    internal class ReturnSetInfo : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ReturnSetInfo;

        public ExprContext econtext { get; set; }

        public tupleDesc expectedDesc { get; set; }

        public int? allowedModes { get; set; }

        public SetFunctionReturnMode? returnMode { get; set; }

        public ExprDoneCond? isDone { get; set; }

        public Tuplestorestate setResult { get; set; }

        public tupleDesc setDesc { get; set; }
    }
}
