/* Generated by QSI

 Date: 2020-08-12
 Span: 24:1 - 32:14
 File: src/postgres/include/rewrite/prs2lock.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class RewriteRule
    {
        public uint? ruleId { get; set; }

        public CmdType? @event { get; set; }

        public IPg10Node qual { get; set; }

        public IPg10Node[] actions { get; set; }

        public char? enabled { get; set; }

        public bool? isInstead { get; set; }
    }
}
