/* Generated by QSI

 Date: 2020-08-07
 Span: 316:1 - 322:15
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum RoleSpecType
    {
        ROLESPEC_CSTRING = 0,
        ROLESPEC_CURRENT_USER = 1,
        ROLESPEC_SESSION_USER = 2,
        ROLESPEC_PUBLIC = 3
    }
}
