/* Generated by QSI

 Date: 2020-08-07
 Span: 324:1 - 330:11
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RoleSpec")]
    internal sealed class RoleSpec : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_RoleSpec; }
        }

        public RoleSpecType roletype { get; set; }

        public string rolename { get; set; }

        public int location { get; set; }
    }
}
