/* Generated by QSI

 Date: 2020-08-07
 Span: 324:1 - 330:11
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RoleSpec")]
    internal class RoleSpec : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_RoleSpec;

        public NodeTag? type { get; set; }

        public RoleSpecType? roletype { get; set; }

        public string rolename { get; set; }
    }
}
