/* Generated by QSI

 Date: 2020-08-12
 Span: 2424:1 - 2429:15
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum RoleStmtType
    {
        ROLESTMT_ROLE = 0,
        ROLESTMT_USER = 1,
        ROLESTMT_GROUP = 2
    }
}
