/* Generated by QSI

 Date: 2020-08-07
 Span: 1479:1 - 1488:13
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("RollupData")]
    internal class RollupData : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_RollupData;

        public NodeTag? type { get; set; }

        public IPg10Node[] groupClause { get; set; }

        public IPg10Node[] gsets { get; set; }

        public IPg10Node[] gsets_data { get; set; }

        public double? numGroups { get; set; }

        public bool? hashable { get; set; }

        public bool? is_hashed { get; set; }
    }
}
