/* Generated by QSI

 Date: 2020-08-07
 Span: 1017:1 - 1026:17
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum RowCompareType
    {
        ROWCOMPARE_LT = 1,
        ROWCOMPARE_LE = 2,
        ROWCOMPARE_EQ = 3,
        ROWCOMPARE_GE = 4,
        ROWCOMPARE_GT = 5,
        ROWCOMPARE_NE = 6
    }
}
