/* Generated by QSI

 Date: 2020-08-07
 Span: 983:1 - 1001:10
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class RowExpr
    {
        public Expr xpr { get; set; }

        public IPg10Node[] args { get; set; }

        public uint row_typeid { get; set; }

        public CoercionForm row_format { get; set; }

        public IPg10Node[] colnames { get; set; }

        public int location { get; set; }
    }
}
