/* Generated by QSI

 Date: 2020-08-07
 Span: 959:1 - 967:14
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum RowMarkType
    {
        ROW_MARK_EXCLUSIVE = 0,
        ROW_MARK_NOKEYEXCLUSIVE = 1,
        ROW_MARK_SHARE = 2,
        ROW_MARK_KEYSHARE = 3,
        ROW_MARK_REFERENCE = 4,
        ROW_MARK_COPY = 5
    }
}
