/* Generated by QSI

 Date: 2020-08-07
 Span: 122:2 - 122:24
 File: src/postgres/include/utils/rel.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class RowSecurityDesc
    {
    }
}
