/* Generated by QSI

 Date: 2020-08-12
 Span: 931:1 - 941:10
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum RTEKind
    {
        RTE_RELATION = 0,
        RTE_SUBQUERY = 1,
        RTE_JOIN = 2,
        RTE_FUNCTION = 3,
        RTE_TABLEFUNC = 4,
        RTE_VALUES = 5,
        RTE_CTE = 6,
        RTE_NAMEDTUPLESTORE = 7
    }
}
