/* Generated by QSI

 Date: 2020-08-07
 Span: 40:1 - 44:11
 File: src/postgres/include/rewrite/prs2lock.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class RuleLock
    {
        public int? numLocks { get; set; }

        public RewriteRule[] rules { get; set; }
    }
}
