/* Generated by QSI

 Date: 2020-08-07
 Span: 342:1 - 347:13
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class SampleScan
    {
        public Scan scan { get; set; }

        public TableSampleClause tablesample { get; set; }
    }
}
