/* Generated by QSI

 Date: 2020-08-07
 Span: 1131:1 - 1143:18
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SampleScanState")]
    internal class SampleScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_SampleScanState;

        public ScanState ss { get; set; }

        public IPg10Node[] args { get; set; }

        public ExprState repeatable { get; set; }

        public TsmRoutine tsmroutine { get; set; }

        public object?[] tsm_state { get; set; }

        public bool? use_bulkread { get; set; }

        public bool? use_pagemode { get; set; }

        public bool? begun { get; set; }

        public uint? seed { get; set; }
    }
}
