/* Generated by QSI

 Date: 2020-08-07
 Span: 536:1 - 545:20
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ScalarArrayOpExpr
    {
        public Expr xpr { get; set; }

        public uint opno { get; set; }

        public uint opfuncid { get; set; }

        public bool useOr { get; set; }

        public uint inputcollid { get; set; }

        public IPg10Node[] args { get; set; }

        public int location { get; set; }
    }
}
