/* Generated by QSI

 Date: 2020-08-12
 Span: 22:1 - 27:16
 File: src/postgres/include/access/sdir.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum ScanDirection
    {
        BackwardScanDirection = -1,
        NoMovementScanDirection = 0,
        ForwardScanDirection = 1
    }
}
