/* Generated by QSI

 Date: 2020-08-07
 Span: 64:1 - 73:14
 File: src/postgres/include/access/skey.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class ScanKeyData
    {
        public int? sk_flags { get; set; }

        public short? sk_attno { get; set; }

        public ushort? sk_strategy { get; set; }

        public uint? sk_subtype { get; set; }

        public uint? sk_collation { get; set; }

        public FmgrInfo sk_func { get; set; }

        public uint? sk_argument { get; set; }
    }
}
