/* Generated by QSI

 Date: 2020-08-07
 Span: 326:1 - 330:7
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Scan
    {
        public Plan plan { get; set; }

        public uint scanrelid { get; set; }
    }
}
