/* Generated by QSI

 Date: 2020-08-07
 Span: 1109:1 - 1115:12
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class ScanState
    {
        public PlanState ps { get; set; }

        public RelationData ss_currentRelation { get; set; }

        public HeapScanDescData ss_currentScanDesc { get; set; }

        public TupleTableSlot ss_ScanTupleSlot { get; set; }
    }
}
