/* Generated by QSI

 Date: 2020-08-12
 Span: 1109:1 - 1115:12
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ScanState")]
    internal class ScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ScanState;

        public PlanState ps { get; set; }

        public RelationData ss_currentRelation { get; set; }

        public HeapScanDescData ss_currentScanDesc { get; set; }

        public TupleTableSlot ss_ScanTupleSlot { get; set; }
    }
}
