/* Generated by QSI

 Date: 2020-08-07
 Span: 2613:1 - 2620:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SecLabelStmt")]
    internal sealed class SecLabelStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_SecLabelStmt; }
        }

        public ObjectType objtype { get; set; }

        public IPg10Node @object { get; set; }

        public string provider { get; set; }

        public string label { get; set; }
    }
}
