/* Generated by QSI

 Date: 2020-08-12
 Span: 1506:1 - 1551:13
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SelectStmt")]
    internal class SelectStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_SelectStmt;

        public IPg10Node[] distinctClause { get; set; }

        public IntoClause[] intoClause { get; set; }

        public IPg10Node[] targetList { get; set; }

        public IPg10Node[] fromClause { get; set; }

        public IPg10Node[] whereClause { get; set; }

        public IPg10Node[] groupClause { get; set; }

        public IPg10Node[] havingClause { get; set; }

        public IPg10Node[] windowClause { get; set; }

        public IPg10Node[] valuesLists { get; set; }

        public IPg10Node[] sortClause { get; set; }

        public IPg10Node[] limitOffset { get; set; }

        public IPg10Node[] limitCount { get; set; }

        public IPg10Node[] lockingClause { get; set; }

        public WithClause[] withClause { get; set; }

        public SetOperation? op { get; set; }

        public bool? all { get; set; }

        public SelectStmt[] larg { get; set; }

        public SelectStmt[] rarg { get; set; }
    }
}
