/* Generated by QSI

 Date: 2020-08-07
 Span: 1121:1 - 1125:15
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class SeqScanState
    {
        public ScanState ss { get; set; }

        public uint pscan_len { get; set; }
    }
}
