/* Generated by QSI

 Date: 2020-08-07
 Span: 248:1 - 254:24
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum SetFunctionReturnMode
    {
        SFRM_ValuePerCall = 1,
        SFRM_Materialize = 2,
        SFRM_Materialize_Random = 4,
        SFRM_Materialize_Preferred = 8
    }
}
