/* Generated by QSI

 Date: 2020-08-12
 Span: 1531:1 - 1541:12
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SetOpPath")]
    internal class SetOpPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_SetOpPath;

        public Path path { get; set; }

        public Path subpath { get; set; }

        public SetOpCmd? cmd { get; set; }

        public SetOpStrategy? strategy { get; set; }

        public IPg10Node[] distinctList { get; set; }

        public short? flagColIdx { get; set; }

        public int? firstFlag { get; set; }

        public double? numGroups { get; set; }
    }
}
