/* Generated by QSI

 Date: 2020-08-07
 Span: 787:1 - 791:16
 File: src/postgres/include/nodes/nodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum SetOpStrategy
    {
        SETOP_SORTED = 0,
        SETOP_HASHED = 1
    }
}
