/* Generated by QSI

 Date: 2020-08-07
 Span: 1991:9 - 1991:38
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class SetOpStatePerGroupData
    {
    }
}
