/* Generated by QSI

 Date: 2020-08-12
 Span: 1253:1 - 1260:15
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SetToDefault")]
    internal class SetToDefault : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_SetToDefault;

        public IPg10Node xpr { get; set; }

        public uint? typeId { get; set; }

        public int? typeMod { get; set; }

        public uint? collation { get; set; }
    }
}
