/* Generated by QSI

 Date: 2020-08-07
 Span: 1303:1 - 1308:20
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum SharedBitmapState
    {
        BM_INITIAL = 0,
        BM_INPROGRESS = 1,
        BM_FINISHED = 2
    }
}
