/* Generated by QSI

 Date: 2020-08-07
 Span: 87:2 - 87:25
 File: src/postgres/include/utils/rel.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class SMgrRelationData
    {
    }
}
