/* Generated by QSI

 Date: 2020-08-12
 Span: 742:1 - 750:7
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Sort")]
    internal class Sort : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Sort;

        public Plan plan { get; set; }

        public int? numCols { get; set; }

        public short[] sortColIdx { get; set; }

        public uint[] sortOperators { get; set; }

        public uint[] collations { get; set; }

        public bool[] nullsFirst { get; set; }
    }
}
