/* Generated by QSI

 Date: 2020-08-07
 Span: 48:1 - 54:12
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum SortByDir
    {
        SORTBY_DEFAULT = 0,
        SORTBY_ASC = 1,
        SORTBY_DESC = 2,
        SORTBY_USING = 3
    }
}
