/* Generated by QSI

 Date: 2020-08-07
 Span: 465:1 - 473:9
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SortBy")]
    internal sealed class SortBy : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_SortBy; }
        }

        public IPg10Node node { get; set; }

        public SortByDir sortby_dir { get; set; }

        public SortByNulls sortby_nulls { get; set; }

        public IPg10Node[] useOp { get; set; }

        public int location { get; set; }
    }
}
