/* Generated by QSI

 Date: 2020-08-07
 Span: 1189:1 - 1197:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SortGroupClause")]
    internal sealed class SortGroupClause : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_SortGroupClause; }
        }

        public uint tleSortGroupRef { get; set; }

        public uint eqop { get; set; }

        public uint sortop { get; set; }

        public bool nulls_first { get; set; }

        public bool hashable { get; set; }
    }
}
