/* Generated by QSI

 Date: 2020-08-07
 Span: 56:1 - 61:14
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum SortByNulls
    {
        SORTBY_NULLS_DEFAULT = 0,
        SORTBY_NULLS_FIRST = 1,
        SORTBY_NULLS_LAST = 2
    }
}
