/* Generated by QSI

 Date: 2020-08-07
 Span: 1750:1 - 1760:12
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class SortState
    {
        public ScanState ss { get; set; }

        public bool randomAccess { get; set; }

        public bool bounded { get; set; }

        public int bound { get; set; }

        public bool sort_Done { get; set; }

        public bool bounded_Done { get; set; }

        public int bound_Done { get; set; }

        public object[] tuplesortstate { get; set; }
    }
}
