/* Generated by QSI

 Date: 2020-08-07
 Span: 1415:1 - 1419:11
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SortPath")]
    internal class SortPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_SortPath;

        public Path path { get; set; }

        public Path subpath { get; set; }
    }
}
