/* Generated by QSI

 Date: 2020-08-07
 Span: 1189:1 - 1197:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SortGroupClause")]
    internal class SortGroupClause : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_SortGroupClause;

        public NodeTag? type { get; set; }

        public uint? tleSortGroupRef { get; set; }

        public uint? eqop { get; set; }

        public uint? sortop { get; set; }

        public bool? nulls_first { get; set; }

        public bool? hashable { get; set; }
    }
}
