/* Generated by QSI

 Date: 2020-08-12
 Span: 60:1 - 193:18
 File: src/postgres/include/utils/sortsupport.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class SortSupportData
    {
        public MemoryContext ssup_cxt { get; set; }

        public uint? ssup_collation { get; set; }

        public bool? ssup_reverse { get; set; }

        public bool? ssup_nulls_first { get; set; }

        public short? ssup_attno { get; set; }

        public object?[] ssup_extra { get; set; }

        public string comparator { get; set; }

        public bool? abbreviate { get; set; }

        public string abbrev_converter { get; set; }

        public string abbrev_abort { get; set; }

        public string abbrev_full_comparator { get; set; }
    }
}
