/* Generated by QSI

 Date: 2020-08-07
 Span: 1101:1 - 1108:19
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class SQLValueFunction
    {
        public Expr xpr { get; set; }

        public SQLValueFunctionOp op { get; set; }

        public uint type { get; set; }

        public int typmod { get; set; }

        public int location { get; set; }
    }
}
