/* Generated by QSI

 Date: 2020-08-07
 Span: 1101:1 - 1108:19
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SQLValueFunction")]
    internal class SQLValueFunction : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_SQLValueFunction;

        public Expr xpr { get; set; }

        public SQLValueFunctionOp? op { get; set; }

        public uint? type { get; set; }

        public int? typmod { get; set; }
    }
}
