/* Generated by QSI

 Date: 2020-08-12
 Span: 1082:1 - 1099:21
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum SQLValueFunctionOp
    {
        SVFOP_CURRENT_DATE = 0,
        SVFOP_CURRENT_TIME = 1,
        SVFOP_CURRENT_TIME_N = 2,
        SVFOP_CURRENT_TIMESTAMP = 3,
        SVFOP_CURRENT_TIMESTAMP_N = 4,
        SVFOP_LOCALTIME = 5,
        SVFOP_LOCALTIME_N = 6,
        SVFOP_LOCALTIMESTAMP = 7,
        SVFOP_LOCALTIMESTAMP_N = 8,
        SVFOP_CURRENT_ROLE = 9,
        SVFOP_CURRENT_USER = 10,
        SVFOP_USER = 11,
        SVFOP_SESSION_USER = 12,
        SVFOP_CURRENT_CATALOG = 13,
        SVFOP_CURRENT_SCHEMA = 14
    }
}
