/* Generated by QSI

 Date: 2020-08-12
 Span: 618:1 - 628:14
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum SubLinkType
    {
        EXISTS_SUBLINK = 0,
        ALL_SUBLINK = 1,
        ANY_SUBLINK = 2,
        ROWCOMPARE_SUBLINK = 3,
        EXPR_SUBLINK = 4,
        MULTIEXPR_SUBLINK = 5,
        ARRAY_SUBLINK = 6,
        CTE_SUBLINK = 7
    }
}
