/* Generated by QSI

 Date: 2020-08-07
 Span: 631:1 - 640:10
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class SubLink
    {
        public Expr xpr { get; set; }

        public SubLinkType subLinkType { get; set; }

        public int subLinkId { get; set; }

        public IPg10Node testexpr { get; set; }

        public IPg10Node[] operName { get; set; }

        public IPg10Node subselect { get; set; }

        public int location { get; set; }
    }
}
