/* Generated by QSI

 Date: 2020-08-12
 Span: 631:1 - 640:10
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SubLink")]
    internal class SubLink : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_SubLink;

        public IPg10Node xpr { get; set; }

        public SubLinkType? subLinkType { get; set; }

        public int? subLinkId { get; set; }

        public IPg10Node testexpr { get; set; }

        public IPg10Node[] operName { get; set; }

        public IPg10Node subselect { get; set; }
    }
}
