/* Generated by QSI

 Date: 2020-08-07
 Span: 1404:1 - 1408:20
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class SubqueryScanState
    {
        public ScanState ss { get; set; }

        public PlanState subplan { get; set; }
    }
}
