/* Generated by QSI

 Date: 2020-08-07
 Span: 495:1 - 499:15
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class SubqueryScan
    {
        public Scan scan { get; set; }

        public Plan subplan { get; set; }
    }
}
