/* Generated by QSI

 Date: 2020-08-12
 Span: 1112:1 - 1116:19
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("SubqueryScanPath")]
    internal class SubqueryScanPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_SubqueryScanPath;

        public Path path { get; set; }

        public Path subpath { get; set; }
    }
}
