/* Generated by QSI

 Date: 2020-08-07
 Span: 1099:1 - 1105:20
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TableSampleClause")]
    internal class TableSampleClause : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_TableSampleClause;

        public NodeTag? type { get; set; }

        public uint? tsmhandler { get; set; }

        public IPg10Node[] args { get; set; }

        public Expr repeatable { get; set; }
    }
}
