/* Generated by QSI

 Date: 2020-08-07
 Span: 1483:8 - 1483:31
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class TableFuncRoutine
    {
    }
}
