/* Generated by QSI

 Date: 2020-08-07
 Span: 79:1 - 95:12
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TableFunc")]
    internal sealed class TableFunc : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_TableFunc; }
        }

        public IPg10Node[] ns_uris { get; set; }

        public IPg10Node[] ns_names { get; set; }

        public IPg10Node docexpr { get; set; }

        public IPg10Node rowexpr { get; set; }

        public IPg10Node[] colnames { get; set; }

        public IPg10Node[] coltypes { get; set; }

        public IPg10Node[] coltypmods { get; set; }

        public IPg10Node[] colcollations { get; set; }

        public IPg10Node[] colexprs { get; set; }

        public IPg10Node[] coldefexprs { get; set; }

        public Bitmapset notnulls { get; set; }

        public int ordinalitycol { get; set; }

        public int location { get; set; }
    }
}
