/* Generated by QSI

 Date: 2020-08-12
 Span: 526:1 - 530:16
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TableFuncScan")]
    internal class TableFuncScan : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_TableFuncScan;

        public Scan scan { get; set; }

        public TableFunc[] tablefunc { get; set; }
    }
}
