/* Generated by QSI

 Date: 2020-08-07
 Span: 526:1 - 530:16
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class TableFuncScan
    {
        public Scan scan { get; set; }

        public TableFunc tablefunc { get; set; }
    }
}
