/* Generated by QSI

 Date: 2020-08-07
 Span: 1472:1 - 1489:21
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class TableFuncScanState
    {
        public ScanState ss { get; set; }

        public ExprState docexpr { get; set; }

        public ExprState rowexpr { get; set; }

        public IPg10Node[] colexprs { get; set; }

        public IPg10Node[] coldefexprs { get; set; }

        public IPg10Node[] ns_names { get; set; }

        public IPg10Node[] ns_uris { get; set; }

        public Bitmapset notnulls { get; set; }

        public object[] opaque { get; set; }

        public TableFuncRoutine routine { get; set; }

        public FmgrInfo in_functions { get; set; }

        public uint typioparams { get; set; }

        public int ordinal { get; set; }

        public MemoryContextData[] perValueCxt { get; set; }

        public Tuplestorestate tupstore { get; set; }
    }
}
