/* Generated by QSI

 Date: 2020-08-12
 Span: 36:1 - 36:39
 File: src/postgres/include/nodes/tidbitmap.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class TBMIterator
    {
    }
}
