/* Generated by QSI

 Date: 2020-08-07
 Span: 40:1 - 47:19
 File: src/postgres/include/nodes/tidbitmap.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class TBMIterateResult
    {
        public uint? blockno { get; set; }

        public int? ntuples { get; set; }

        public bool? recheck { get; set; }

        public ushort? offsets { get; set; }
    }
}
