/* Generated by QSI

 Date: 2020-08-12
 Span: 37:1 - 37:51
 File: src/postgres/include/nodes/tidbitmap.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class TBMSharedIterator
    {
    }
}
