/* Generated by QSI

 Date: 2020-08-07
 Span: 33:1 - 33:35
 File: src/postgres/include/nodes/tidbitmap.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class TIDBitmap
    {
    }
}
