/* Generated by QSI

 Date: 2020-08-12
 Span: 33:1 - 33:35
 File: src/postgres/include/nodes/tidbitmap.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TIDBitmap")]
    internal class TIDBitmap : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_TIDBitmap;
    }
}
