/* Generated by QSI

 Date: 2020-08-07
 Span: 1386:1 - 1395:15
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class TidScanState
    {
        public ScanState ss { get; set; }

        public IPg10Node[] tss_tidexprs { get; set; }

        public bool tss_isCurrentOf { get; set; }

        public int tss_NumTids { get; set; }

        public int tss_TidPtr { get; set; }

        public ItemPointerData tss_TidList { get; set; }

        public HeapTupleData tss_htup { get; set; }
    }
}
