/* Generated by QSI

 Date: 2020-08-07
 Span: 473:1 - 477:10
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class TidScan
    {
        public Scan scan { get; set; }

        public IPg10Node[] tidquals { get; set; }
    }
}
