/* Generated by QSI

 Date: 2020-08-07
 Span: 473:1 - 477:10
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TidScan")]
    internal class TidScan : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_TidScan;

        public Scan scan { get; set; }

        public IPg10Node[] tidquals { get; set; }
    }
}
