/* Generated by QSI

 Date: 2020-08-12
 Span: 1386:1 - 1395:15
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TidScanState")]
    internal class TidScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_TidScanState;

        public ScanState ss { get; set; }

        public IPg10Node[] tss_tidexprs { get; set; }

        public bool? tss_isCurrentOf { get; set; }

        public int? tss_NumTids { get; set; }

        public int? tss_TidPtr { get; set; }

        public ItemPointerData tss_TidList { get; set; }

        public HeapTupleData tss_htup { get; set; }
    }
}
