/* Generated by QSI

 Date: 2020-08-07
 Span: 33:1 - 37:2
 File: ../../../../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_timespec.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class timespec
    {
        public int tv_sec { get; set; }

        public int tv_nsec { get; set; }
    }
}
