/* Generated by QSI

 Date: 2020-08-07
 Span: 2931:1 - 2937:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TransactionStmt")]
    internal sealed class TransactionStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_TransactionStmt; }
        }

        public TransactionStmtKind kind { get; set; }

        public IPg10Node[] options { get; set; }

        public string gid { get; set; }
    }
}
