/* Generated by QSI

 Date: 2020-08-12
 Span: 2931:1 - 2937:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TransactionStmt")]
    internal class TransactionStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_TransactionStmt;

        public TransactionStmtKind? kind { get; set; }

        public IPg10Node[] options { get; set; }

        public string gid { get; set; }
    }
}
