/* Generated by QSI

 Date: 2020-08-12
 Span: 30:1 - 42:14
 File: src/postgres/include/commands/trigger.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TriggerData")]
    internal class TriggerData : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_TriggerData;

        public uint? tg_event { get; set; }

        public RelationData[] tg_relation { get; set; }

        public HeapTupleData[] tg_trigtuple { get; set; }

        public HeapTupleData[] tg_newtuple { get; set; }

        public Trigger[] tg_trigger { get; set; }

        public int? tg_trigtuplebuf { get; set; }

        public int? tg_newtuplebuf { get; set; }

        public Tuplestorestate[] tg_oldtable { get; set; }

        public Tuplestorestate[] tg_newtable { get; set; }
    }
}
