/* Generated by QSI

 Date: 2020-08-07
 Span: 2589:1 - 2595:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TruncateStmt")]
    internal sealed class TruncateStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_TruncateStmt; }
        }

        public IPg10Node[] relations { get; set; }

        public bool restart_seqs { get; set; }

        public DropBehavior behavior { get; set; }
    }
}
