/* Generated by QSI

 Date: 2020-08-07
 Span: 1137:2 - 1137:19
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class TsmRoutine
    {
    }
}
