/* Generated by QSI

 Date: 2020-08-12
 Span: 1137:2 - 1137:19
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TsmRoutine")]
    internal class TsmRoutine : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_TsmRoutine;
    }
}
