/* Generated by QSI

 Date: 2020-08-07
 Span: 40:1 - 40:47
 File: src/postgres/include/utils/tuplestore.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class Tuplestorestate
    {
    }
}
