/* Generated by QSI

 Date: 2020-08-07
 Span: 21:1 - 30:21
 File: src/postgres/include/access/tupconvert.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class TupleConversionMap
    {
        public tupleDesc indesc { get; set; }

        public tupleDesc outdesc { get; set; }

        public short? attrMap { get; set; }

        public uint? invalues { get; set; }

        public bool?[] inisnull { get; set; }

        public uint? outvalues { get; set; }

        public bool?[] outisnull { get; set; }
    }
}
