/* Generated by QSI

 Date: 2020-08-07
 Span: 605:1 - 621:23
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class TupleHashTableData
    {
        public tuplehash_hash hashtab { get; set; }

        public int numCols { get; set; }

        public short keyColIdx { get; set; }

        public FmgrInfo tab_hash_funcs { get; set; }

        public FmgrInfo tab_eq_funcs { get; set; }

        public MemoryContextData[] tablecxt { get; set; }

        public MemoryContextData[] tempcxt { get; set; }

        public uint entrysize { get; set; }

        public TupleTableSlot tableslot { get; set; }

        public TupleTableSlot inputslot { get; set; }

        public FmgrInfo in_hash_funcs { get; set; }

        public FmgrInfo cur_eq_funcs { get; set; }

        public uint hash_iv { get; set; }
    }
}
