/* Generated by QSI

 Date: 2020-08-07
 Span: 1935:2 - 1935:25
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class TupleQueueReader
    {
    }
}
