/* Generated by QSI

 Date: 2020-08-12
 Span: 37:9 - 44:2
 File: src/postgres/include/access/tupdesc.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class tupleConstr
    {
        public attrDefault defval { get; set; }

        public constrCheck check { get; set; }

        public ushort? num_defval { get; set; }

        public ushort? num_check { get; set; }

        public bool? has_not_null { get; set; }
    }
}
