/* Generated by QSI

 Date: 2020-08-07
 Span: 32:1 - 32:45
 File: src/postgres/include/utils/tuplesort.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Tuplesortstate
    {
    }
}
