/* Generated by QSI

 Date: 2020-08-07
 Span: 132:1 - 137:16
 File: src/postgres/include/lib/simplehash.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class tuplehash_iterator
    {
        public uint? cur { get; set; }

        public uint? end { get; set; }

        public bool? done { get; set; }
    }
}
