/* Generated by QSI

 Date: 2020-08-12
 Span: 589:1 - 595:21
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class TupleHashEntryData
    {
        public MinimalTupleData[] firstTuple { get; set; }

        public object[] additional { get; set; }

        public uint? status { get; set; }

        public uint? hash { get; set; }
    }
}
