/* Generated by QSI

 Date: 2020-08-07
 Span: 294:1 - 300:11
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TypeCast")]
    internal sealed class TypeCast : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_TypeCast; }
        }

        public IPg10Node arg { get; set; }

        public TypeName typeName { get; set; }

        public int location { get; set; }
    }
}
