/* Generated by QSI

 Date: 2020-08-07
 Span: 294:1 - 300:11
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TypeCast")]
    internal class TypeCast : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_TypeCast;

        public NodeTag? type { get; set; }

        public IPg10Node arg { get; set; }

        public TypeName typeName { get; set; }
    }
}
