/* Generated by QSI

 Date: 2020-08-07
 Span: 205:1 - 216:11
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("TypeName")]
    internal sealed class TypeName : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_TypeName; }
        }

        public IPg10Node[] names { get; set; }

        public uint typeOid { get; set; }

        public bool setof { get; set; }

        public bool pct_type { get; set; }

        public IPg10Node[] typmods { get; set; }

        public int typemod { get; set; }

        public IPg10Node[] arrayBounds { get; set; }

        public int location { get; set; }
    }
}
