/* Generated by QSI

 Date: 2020-08-07
 Span: 818:1 - 824:9
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Unique
    {
        public Plan plan { get; set; }

        public int numCols { get; set; }

        public short uniqColIdx { get; set; }

        public uint uniqOperators { get; set; }
    }
}
