/* Generated by QSI

 Date: 2020-08-07
 Span: 1241:1 - 1246:19
 File: src/postgres/include/nodes/relation.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum UniquePathMethod
    {
        UNIQUE_PATH_NOOP = 0,
        UNIQUE_PATH_HASH = 1,
        UNIQUE_PATH_SORT = 2
    }
}
