/* Generated by QSI

 Date: 2020-08-07
 Span: 1909:1 - 1914:14
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class UniqueState
    {
        public PlanState ps { get; set; }

        public FmgrInfo eqfunctions { get; set; }

        public MemoryContextData[] tempContext { get; set; }
    }
}
