/* Generated by QSI

 Date: 2020-08-12
 Span: 1909:1 - 1914:14
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("UniqueState")]
    internal class UniqueState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_UniqueState;

        public PlanState ps { get; set; }

        public FmgrInfo[] eqfunctions { get; set; }

        public MemoryContext tempContext { get; set; }
    }
}
