/* Generated by QSI

 Date: 2020-08-12
 Span: 1248:1 - 1255:13
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("UniquePath")]
    internal class UniquePath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_UniquePath;

        public Path path { get; set; }

        public Path[] subpath { get; set; }

        public UniquePathMethod? umethod { get; set; }

        public IPg10Node[] in_operators { get; set; }

        public IPg10Node[] uniq_exprs { get; set; }
    }
}
