/* Generated by QSI

 Date: 2020-08-07
 Span: 2907:1 - 2911:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("UnlistenStmt")]
    internal sealed class UnlistenStmt : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_UnlistenStmt; }
        }

        public string conditionname { get; set; }
    }
}
