/* Generated by QSI

 Date: 2020-08-12
 Span: 1443:1 - 1448:18
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("UpperUniquePath")]
    internal class UpperUniquePath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_UpperUniquePath;

        public Path path { get; set; }

        public Path subpath { get; set; }

        public int? numkeys { get; set; }
    }
}
