/* Generated by QSI

 Date: 2020-08-12
 Span: 3101:1 - 3107:13
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("VacuumStmt")]
    internal class VacuumStmt : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_VacuumStmt;

        public int? options { get; set; }

        public RangeVar relation { get; set; }

        public IPg10Node[] va_cols { get; set; }
    }
}
