/* Generated by QSI

 Date: 2020-08-12
 Span: 42:1 - 50:8
 File: src/postgres/include/nodes/value.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class Value : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Value;

        public int? ival { get; set; }

        public string str { get; set; }
    }
}
