/* Generated by QSI

 Date: 2020-08-07
 Span: 42:1 - 50:8
 File: src/postgres/include/nodes/value.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Value")]
    internal class Value : IPg10Node
    {
        public virtual NodeTag Type
        {
            get { return NodeTag.T_Value; }
        }

        public int ival { get; set; }

        public string str { get; set; }
    }
}
