/* Generated by QSI

 Date: 2020-08-07
 Span: 516:1 - 520:13
 File: src/postgres/include/nodes/plannodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ValuesScan")]
    internal class ValuesScan : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ValuesScan;

        public Scan scan { get; set; }

        public IPg10Node[] values_lists { get; set; }
    }
}
