/* Generated by QSI

 Date: 2020-08-12
 Span: 1457:1 - 1464:18
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("ValuesScanState")]
    internal class ValuesScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_ValuesScanState;

        public ScanState ss { get; set; }

        public ExprContext rowcontext { get; set; }

        public IPg10Node[][] exprlists { get; set; }

        public int? array_len { get; set; }

        public int? curr_idx { get; set; }
    }
}
