/* Generated by QSI

 Date: 2020-08-07
 Span: 163:1 - 179:6
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class Var
    {
        public Expr xpr { get; set; }

        public uint varno { get; set; }

        public short varattno { get; set; }

        public uint vartype { get; set; }

        public int vartypmod { get; set; }

        public uint varcollid { get; set; }

        public uint varlevelsup { get; set; }

        public uint varnoold { get; set; }

        public short varoattno { get; set; }

        public int location { get; set; }
    }
}
