/* Generated by QSI

 Date: 2020-08-12
 Span: 163:1 - 179:6
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("Var")]
    internal class Var : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_Var;

        public IPg10Node xpr { get; set; }

        public uint? varno { get; set; }

        public short? varattno { get; set; }

        public uint? vartype { get; set; }

        public int? vartypmod { get; set; }

        public uint? varcollid { get; set; }

        public uint? varlevelsup { get; set; }

        public uint? varnoold { get; set; }

        public short? varoattno { get; set; }
    }
}
