/* Generated by QSI

 Date: 2020-08-12
 Span: 1960:1 - 1968:18
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum VariableSetKind
    {
        VAR_SET_VALUE = 0,
        VAR_SET_DEFAULT = 1,
        VAR_SET_CURRENT = 2,
        VAR_SET_MULTI = 3,
        VAR_RESET = 4,
        VAR_RESET_ALL = 5
    }
}
