/* Generated by QSI

 Date: 2020-08-12
 Span: 517:1 - 521:2
 File: src/postgres/include/c.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class varlena
    {
        public string vl_len_ { get; set; }

        public string vl_dat { get; set; }
    }
}
