/* Generated by QSI

 Date: 2020-08-07
 Span: 2991:1 - 2996:18
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum ViewCheckOption
    {
        NO_CHECK_OPTION = 0,
        LOCAL_CHECK_OPTION = 1,
        CASCADED_CHECK_OPTION = 2
    }
}
