/* Generated by QSI

 Date: 2020-08-07
 Span: 1113:1 - 1119:10
 File: src/postgres/include/nodes/parsenodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum WCOKind
    {
        WCO_VIEW_CHECK = 0,
        WCO_RLS_INSERT_CHECK = 1,
        WCO_RLS_UPDATE_CHECK = 2,
        WCO_RLS_CONFLICT_CHECK = 3
    }
}
