/* Generated by QSI

 Date: 2020-08-07
 Span: 1520:1 - 1526:16
 File: src/postgres/include/nodes/relation.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("WindowAggPath")]
    internal class WindowAggPath : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_WindowAggPath;

        public Path path { get; set; }

        public Path subpath { get; set; }

        public WindowClause winclause { get; set; }

        public IPg10Node[] winpathkeys { get; set; }
    }
}
