/* Generated by QSI

 Date: 2020-08-07
 Span: 799:1 - 812:12
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class WindowAgg
    {
        public Plan plan { get; set; }

        public uint winref { get; set; }

        public int partNumCols { get; set; }

        public short partColIdx { get; set; }

        public uint partOperators { get; set; }

        public int ordNumCols { get; set; }

        public short ordColIdx { get; set; }

        public uint ordOperators { get; set; }

        public int frameOptions { get; set; }

        public IPg10Node startOffset { get; set; }

        public IPg10Node endOffset { get; set; }
    }
}
