/* Generated by QSI

 Date: 2020-08-07
 Span: 483:1 - 494:12
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("WindowDef")]
    internal class WindowDef : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_WindowDef;

        public NodeTag? type { get; set; }

        public string name { get; set; }

        public string refname { get; set; }

        public IPg10Node[] partitionClause { get; set; }

        public IPg10Node[] orderClause { get; set; }

        public int? frameOptions { get; set; }

        public IPg10Node startOffset { get; set; }

        public IPg10Node endOffset { get; set; }
    }
}
