/* Generated by QSI

 Date: 2020-08-07
 Span: 1840:9 - 1840:38
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class WindowStatePerFuncData
    {
    }
}
