/* Generated by QSI

 Date: 2020-08-07
 Span: 667:1 - 674:22
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("WindowFuncExprState")]
    internal sealed class WindowFuncExprState : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_WindowFuncExprState; }
        }

        public WindowFunc wfunc { get; set; }

        public IPg10Node[] args { get; set; }

        public ExprState aggfilter { get; set; }

        public int wfuncno { get; set; }
    }
}
