/* Generated by QSI

 Date: 2020-08-07
 Span: 1280:1 - 1292:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("WindowClause")]
    internal sealed class WindowClause : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_WindowClause; }
        }

        public string name { get; set; }

        public string refname { get; set; }

        public IPg10Node[] partitionClause { get; set; }

        public IPg10Node[] orderClause { get; set; }

        public int frameOptions { get; set; }

        public IPg10Node startOffset { get; set; }

        public IPg10Node endOffset { get; set; }

        public uint winref { get; set; }

        public bool copiedOrder { get; set; }
    }
}
