/* Generated by QSI

 Date: 2020-08-07
 Span: 1863:2 - 1863:25
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("WindowObjectData")]
    internal class WindowObjectData : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_WindowObjectData;
    }
}
