/* Generated by QSI

 Date: 2020-08-12
 Span: 1841:9 - 1841:37
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class WindowStatePerAggData
    {
    }
}
