/* Generated by QSI

 Date: 2020-08-07
 Span: 483:1 - 494:12
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("WindowDef")]
    internal sealed class WindowDef : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_WindowDef; }
        }

        public string name { get; set; }

        public string refname { get; set; }

        public IPg10Node[] partitionClause { get; set; }

        public IPg10Node[] orderClause { get; set; }

        public int frameOptions { get; set; }

        public IPg10Node startOffset { get; set; }

        public IPg10Node endOffset { get; set; }

        public int location { get; set; }
    }
}
