/* Generated by QSI

 Date: 2020-08-07
 Span: 1863:2 - 1863:25
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class WindowObjectData
    {
    }
}
