/* Generated by QSI

 Date: 2020-08-12
 Span: 1322:1 - 1328:13
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("WithClause")]
    internal class WithClause : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_WithClause;

        public IPg10Node[] ctes { get; set; }

        public bool? recursive { get; set; }
    }
}
