/* Generated by QSI

 Date: 2020-08-07
 Span: 1121:1 - 1129:18
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("WithCheckOption")]
    internal class WithCheckOption : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_WithCheckOption;

        public NodeTag? type { get; set; }

        public WCOKind? kind { get; set; }

        public string relname { get; set; }

        public string polname { get; set; }

        public IPg10Node qual { get; set; }

        public bool? cascaded { get; set; }
    }
}
