/* Generated by QSI

 Date: 2020-08-07
 Span: 66:1 - 70:24
 File: src/postgres/include/executor/instrument.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal class WorkerInstrumentation
    {
        public int? num_workers { get; set; }

        public Instrumentation instrument { get; set; }
    }
}
