/* Generated by QSI

 Date: 2020-08-07
 Span: 1540:1 - 1544:21
 File: src/postgres/include/nodes/execnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class WorkTableScanState
    {
        public ScanState ss { get; set; }

        public RecursiveUnionState rustate { get; set; }
    }
}
