/* Generated by QSI

 Date: 2020-08-07
 Span: 557:1 - 561:16
 File: src/postgres/include/nodes/plannodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal sealed class WorkTableScan
    {
        public Scan scan { get; set; }

        public int wtParam { get; set; }
    }
}
