/* Generated by QSI

 Date: 2020-08-12
 Span: 1540:1 - 1544:21
 File: src/postgres/include/nodes/execnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("WorkTableScanState")]
    internal class WorkTableScanState : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_WorkTableScanState;

        public ScanState ss { get; set; }

        public RecursiveUnionState[] rustate { get; set; }
    }
}
