/* Generated by QSI

 Date: 2020-08-12
 Span: 1121:1 - 1131:12
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum XmlExprOp
    {
        IS_XMLCONCAT = 0,
        IS_XMLELEMENT = 1,
        IS_XMLFOREST = 2,
        IS_XMLPARSE = 3,
        IS_XMLPI = 4,
        IS_XMLROOT = 5,
        IS_XMLSERIALIZE = 6,
        IS_DOCUMENT = 7
    }
}
