/* Generated by QSI

 Date: 2020-08-12
 Span: 1139:1 - 1151:10
 File: src/postgres/include/nodes/primnodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("XmlExpr")]
    internal class XmlExpr : IPg10Node
    {
        public virtual NodeTag Type => NodeTag.T_XmlExpr;

        public IPg10Node xpr { get; set; }

        public XmlExprOp? op { get; set; }

        public string name { get; set; }

        public IPg10Node[] named_args { get; set; }

        public IPg10Node[] arg_names { get; set; }

        public IPg10Node[] args { get; set; }

        public XmlOptionType? xmloption { get; set; }

        public uint? type { get; set; }

        public int? typmod { get; set; }
    }
}
