/* Generated by QSI

 Date: 2020-08-12
 Span: 1133:1 - 1137:16
 File: src/postgres/include/nodes/primnodes.h

*/

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    internal enum XmlOptionType
    {
        XMLOPTION_DOCUMENT = 0,
        XMLOPTION_CONTENT = 1
    }
}
