/* Generated by QSI

 Date: 2020-08-07
 Span: 748:1 - 755:15
 File: src/postgres/include/nodes/parsenodes.h

*/

using Qsi.PostgreSql.Internal.Serialization;

namespace Qsi.PostgreSql.Internal.PG10.Types
{
    [PgNode("XmlSerialize")]
    internal sealed class XmlSerialize : IPg10Node
    {
        public NodeTag Type
        {
            get { return NodeTag.T_XmlSerialize; }
        }

        public XmlOptionType xmloption { get; set; }

        public IPg10Node expr { get; set; }

        public TypeName typeName { get; set; }

        public int location { get; set; }
    }
}
